"""Build the SIH26166 deck into the official template, from the content in this folder.

    python -m presentation.build_deck

Inputs   presentation/sih_template.pptx   (924,505 bytes, sha256 ce3e5dee...)
         presentation/figures/*.png       (generated by presentation.make_figures)
Output   presentation/SIH26166_LunaXX_deck.pptx   (national round, v6 - 22 Sep 2026)

V6 (NATIONAL ROUND, the 22 Sep pitch pass). V5 was correct and read like a lab report: slides 2
and 4 carried 278 and 272 words of ours and the thesis was the last bullet on slide 2. V6 keeps
every figure and every condition and changes the argument's shape - the thesis leads slide 1 and
slide 2, the eight-box pipeline recitation is gone from slide 2 because slide 3 draws it, the
limits on slide 4 are stated as the field's rather than ours, and slide 5 opens on who it is for.
Two SAC hooks were added and both were checked before use: the polar pair, where their own study
found only SuperGlue registered it (REPORT.md:97,121), and their 2026 mosaic paper's statement
that it does not address geometric misalignment (arXiv:2604.25208 SS VI, read 22 Sep). No accuracy
comparison with arXiv:2509.04775 is made anywhere, deliberately: their SuperGlue figure is 0.69 m
and our best in-sample on that pair is 1.06 m.

The claim-check after the rewrite found five things and all five are fixed here: the synthetic
0.086 px is the 0-15 deg value of four and now says so; the multi-modal px carries its metres;
"3 px out" was in no row (the trials are planted in metres over four grids) and is now stated in
metres with its trial counts; slide 1 said "every region of every result" where the 112-px IIRS
windows get a whole-frame verdict; and slide 6's provenance sentence was wrong for the second
round running - only real_pairs_log.csv is stamped 7dd4e5b, MiLOI is "run e10deb0, scored
7dd4e5b", and two logs carry no commit column at all.

Body type on slides 3-6 dropped one notch to pay for those additions; slide 3's flow chart and
slide 4's scatter were narrowed to give their text more room.

V4 (NATIONAL ROUND, after both passes of the 20 Sep audit). The text below is rebuilt around the
real-data evidence of 18-20 Sep (REPORT.md). Every number on a slide was copied from the REPORT.md
generated at f928995, whose real-pair rows were measured at the evidence-freeze commit 7dd4e5b
(FROZEN, 10/10 steps, 183 rows), and the comment beside it
names the REPORT.md section it came from. A new freeze means re-reading every one of them. The
audit still counts "TBD". The college-round deck (SIH26166_deck.pptx, built by this file up to
1864ad3) is not overwritten; the pre-audit v2 is tagged submission-v1.

WHAT THE OFFICIAL INSTRUCTIONS SLIDE ACTUALLY SAYS, and how each line is honoured here:

  "Kindly keep the maximum slides limit up to six (6). (Including the title slide)"
      -> we ship exactly 6. The instructions slide (7) is deleted, which that slide
         explicitly permits.
  "Try to avoid paragraphs and post your idea in points /diagrams /Infographics /pictures"
      -> every content block is bullets, and every content slide carries a generated
         figure: the trust map itself (2), the pipeline flowchart (3), the sun-angle
         curve (4), the calibration curve (5).
  "You can only use provided template ... without changing the idea details pointers
   (mentioned in previous slides)."
      -> THE POINTER TEXT IS NEVER EDITED. Not one character. It is moved under the
         title bar and set small and grey so it reads as the section guide it is, and
         our content goes in NEW text boxes below it. Moving a box does not change a
         pointer; rewriting it would. This is the conservative reading and it is the one
         we take, because the cost of being wrong is disqualification. The build checks
         this itself at the end of a run (see `_check_pointers`).
  "You need to save the file in PDF and upload the same on portal."
      -> the .pptx is the source; export to PDF before uploading. See the note printed
         at the end of a run.

Layout facts of the template that this file works around (measured with python-pptx):
  slide 13.33 x 7.5 in · "Your Team Name" oval at (0.36, 0.28) 1.37 x 0.88 in · title
  placeholder spans y -0.05..1.20 · SIH logo at (10.70, 0) 2.46 x 1.16 in · footer bar
  from y 6.95. The 4 Sep build put the pointers at y 1.06 and they printed straight
  through the oval on every content slide; they now start at y 1.20, below both.

Every number that appears on a slide is in the evidence logs (evaluation/*.csv, rendered by
ops/make_report.py into REPORT.md), or is a documented instrument/literature fact. The v2 audit
table is presentation/DECK_V2_DRAFT.md (DECK_CONTENT.md is the college round's). This file is
the only place deck prose lives in code - if a figure changes, re-run make_figures; if a number
changes, fix it here and in DECK_V2_DRAFT.md and re-run.

Audience (national round): SAC-ISRO image-processing scientists reading the PDF cold, ranking
it against every other SIH26166 idea. Novelty is 25 % of the college rubric; the national one
is not published. What they can check in ten seconds: the pair IDs from their own paper
(arXiv:2509.04775, Table 1), and whether "cross-sensor" / "multi-modal" / "sub-pixel" are used
the way Invariant 2 defines them.
"""
from __future__ import annotations

import pathlib
import re
import subprocess
import sys

from PIL import Image
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.oxml.ns import qn
from pptx.util import Emu, Inches, Pt

HERE = pathlib.Path(__file__).resolve().parent
TEMPLATE = HERE / "sih_template.pptx"
FIGURES = HERE / "figures"
OUT = HERE / "SIH26166_LunaXX_deck.pptx"

INK = RGBColor(0x1A, 0x1A, 0x1A)
MUTED = RGBColor(0x60, 0x60, 0x60)
BLUE = RGBColor(0x1F, 0x5C, 0xA8)
ACCENT = RGBColor(0xC2, 0x4A, 0x1E)

# EVERY run we write names this font for latin, East Asian AND complex-script ranges.
#
# The template's theme declares <a:latin typeface="Calibri"/> but leaves <a:ea/> and
# <a:cs/> EMPTY. A run that inherits that has no font for any glyph PowerPoint classifies
# outside the latin range, so it resolves ° and × through font linking to a system East
# Asian face with full-width metrics - which is why the 9 Sep build rendered
# "at a 15°   sun difference" and "2.88 ×  better", with gaps we never typed. Calibri
# carries every character this deck uses (° × ± → ↔ ≤ — – ·), so naming it in all three
# ranges removes the fallback entirely.
BODY_FONT = "Calibri"

# National-round portal values. The team name on the portal is LunaXX (nominated 18 Sep; the
# 2026 guidelines forbid the institute's name in a team name - the college-round deck said
# "SNPSU LunaX"). The Team ID is the portal's, as Samartha read it on 20 Sep: SNPSU0192. It
# carries the institute's code, which is allowed - the rule is about the team NAME.
TEAM_ID = "SNPSU0192"
TEAM_NAME = "LunaXX"

# Labels copied from the template's own title block, separator included, rather than
# reworded with colons: the template writes "Problem Statement ID –", "Theme-",
# "Team Name (Registered on portal)". Only the values after them are ours.
TITLE_META = [
    ("Problem Statement ID –", "SIH26166"),
    ("Problem Statement Title-", "Multi-modal, Sun angle and scale invariant image "
                                 "correspondence using Chandrayaan-2 optical images "
                                 "(OHRC, TMC and IIRS)"),
    ("Theme-", "Space Technology"),
    ("PS Category-", "Software"),
    ("Team ID-", TEAM_ID),
    ("Team Name (Registered on portal)-", TEAM_NAME),
]

# The thesis, on the title page, in the empty band under the metadata block.
TITLE_LINE_BOX = (0.36, 4.98, 6.30, 1.60)
TITLE_LINE = [
    ("Registration that knows when it is wrong", 0, True, ACCENT),
        ("A verdict for every region of the result, from an independent check that never sees "
     "the matches it is judging — and calibrated on real lunar imagery, not asserted.",
     1, False, INK),
]

# Geometry (inches). Content sits under the pointer box, above the footer bar. The right
# margin matches the left one: 0.55 in each side, so the content band is 0.55..12.78. The
# 9 Sep build put side figures at 7.45 + 5.50 = 12.95, leaving 0.38 in on the right against
# 0.55 in on the left - a visible asymmetry against the template's centred title.
POINTER_BOX = (0.55, 1.24, 12.2, 0.44)   # below the oval (ends 1.16) and the title text
# The pointer box's four-line worst case (slide 2, 8 pt) ends at 1.68; the footer bar
# starts at 6.95. TOP/BOTTOM take the rest, which is what keeps slide 4 - the densest -
# off its ceiling.
TOP, BOTTOM = 1.74, 6.90
LEFT_COL = (0.55, TOP, 6.55, BOTTOM - TOP)          # text column beside a figure
RIGHT_FIG = (7.28, 5.50)                            # (left, width) of a side figure
# Slide 2 answers FOUR pointers where slides 4 and 5 answer three and two, so its figure
# is the STACKED trust map (5.0 x 7.2 in canvas): narrow and tall, which leaves the text
# 8.33 in instead of 6.55 and still lands every label above the 6 pt on-slide floor.
S2_COL = (0.55, TOP, 8.48, BOTTOM - TOP)
S2_FIG = (9.33, 3.45)
FULL = (0.55, TOP, 12.23, BOTTOM - TOP)
BULLET_INDENT = 0.26                                # hanging indent for wrapped bullets

# (text, level, bold, colour). Level 0 is a heading, 1 a bullet.
#
# EVERY HEADING IS ONE OF THE TEMPLATE'S OWN POINTERS, in the template's order.
#
# The 9 Sep build used headings we invented — "The finding, not the feature", "Risks -
# stated by us, with numbers", "Built, tested, usable", "Trust as a deliverable". They read
# as commentary on our own work rather than as answers, which is what makes a deck feel
# machine-written; worse, slide 2 never answered "Detailed explanation of the proposed
# solution" at all, because the how-it-works had been left on slide 3. Round 1 is screened
# from the file with nobody presenting, so an evaluator reads down the grey pointers and
# looks for each one in turn. Each is now a heading directly beneath them.
# V3 CONTENT. Every number was filled at the evidence freeze (b678272) from the source in its comment
# (REPORT.md section names are the headings `python -m ops.make_report` writes). Invariant 2:
# OHRC<->NAC / OHRC<->TC are cross-sensor AND cross-mission; OHRC<->TMC-2 is cross-sensor, same
# mission; NAC<->NAC (MiLOI, the sweep's NAC legs) and TMC-2 fore<->aft are SAME sensor; only
# visible<->infrared (MI, IIRS) and optical<->elevation (LOLA) are multi-modal.
S2 = [
    ("Proposed Solution", 0, True, BLUE),
    # The thesis, in the first line a judge reads. v5 buried it under four pointers of method.
    ("Every lunar registration method returns an answer. Ours returns the answer AND a verdict "
     "on it — region by region, from a test that never sees the matches it is judging.",
     1, True, ACCENT),
    ("Detailed explanation", 0, True, BLUE),
    # The eight boxes are DRAWN on slide 3. Here, only the one that is ours.
    ("A standard pipeline registers (slide 3). Ours adds what runs next: an independent area "
     "check that cross-correlates the warped image against the reference in 8×8 cells and never "
     "reads a match position — so it can contradict the matcher that produced them.",
     1, False, INK),
    
        ("How it addresses the problem", 0, True, BLUE),
    ("Measured, not designed: 160 distinct ground windows, 8 instrument pairings, real "
     "Chandrayaan-2, LRO, Kaguya and LOLA data.", 1, False, INK),
    # REPORT.md "SAC's own benchmark pair (equatorial ...)": count of `agrees` / rows.
    # "Real sun-angle sweep": the "All bins" line, and the "failed, not caught" column, 0 in
    # all six bins.
    # REPORT.md lines 97 and 121 record what the paper reports: "only SuperGlue registered the
    # polar one". Ours: 4 agrees, 1 unconfirmed, 1 contradicted = 4/6 accepted, 2 flagged.
    # A did-it-register fact, NOT an accuracy comparison: on the equatorial pair SAC's SuperGlue
    # in-sample figure is 0.62 px x 1.118 m = 0.69 m and ours is 0.656 px x 1.622 m = 1.06 m at
    # best (REPORT.md in-sample table), so no accuracy comparison with the paper goes on a slide.
        ("Sun angle, on SAC's own benchmark pairs (arXiv:2509.04775): equatorial, Suns 174° apart "
     "and every shadow reversed — 6/6 windows accepted. On the polar pair, where their study "
     "found only SuperGlue registered it at all, our check vouches for 4 of our 6 windows and "
     "flags 2 — a different measure from theirs (pair registered vs. windows vouched for), and "
     "we say so.", 1, False, INK),
    ("Our own Sun sweep: one OHRC frame against 25 NAC frames, 69 windows, Suns "
     "3.3–152.7° apart — zero undetected failures.", 1, False, INK),
    # "Scale rung: ... TC ortho map": scale column, `agrees` / rows. REPORT.md footer: 160.
    # "Kaguya TC -> Kaguya MI": 1548 nm declared fallback / rows; its "Fallback vs the visible
    # band" table -> disagreement median px range, on MI's grid.
    ("Scale: 29.6×, OHRC at 0.25 m onto Kaguya TC at 7.4 m, 3/4 accepted. Multi-modal: "
     "visible against infrared is refused on 3/3 windows, and the declared fallback still lands "
     "within 0.23–1.09 px = 3.4–16.2 m of the visible-band fit, on MI's 14.8 m grid.",
     1, False, INK),
    ("Innovation and uniqueness", 0, True, ACCENT),
    # "Trust layer on real imagery: planted ...", both populations: 0 m row = false alarms;
    # >= 5 m rows; the 1-2 m rows are the stated floor. 30 real windows: REPORT.md, the
    # trust_real_calibration preamble. Two "0/N" in one sentence, the first a strength and the
    # second a weakness: the floor is named as a floor so it cannot be read the flattering way
    # (claim-checker M5, v4).
    # NOT "30 real windows: 100% of 5 m errors flagged" (pass 2): 30 = 22 near-Sun + 8 SAC, and
    # SAC's 8 flag 84.4 % at 5 m, so the pooled 5 m rate is 230/240. Each rate keeps its population.
    ("Anyone can claim a failure detector. We can show ours is calibrated. Plant a wrong answer "
     "of known size in 30 real windows: 0/44 and 0/16 false alarms across the two Sun "
     "populations, never pooled; every 5 m error flagged "
     "with the Suns within 10°, every 10 m error with them 132–174° apart "
     "— and almost nothing caught below 2 m, a floor we print rather than hide.",
     1, True, ACCENT),
]

S3_LEFT = [
    ("Technologies to be used", 0, True, BLUE),
    ("Python · OpenCV · PyTorch, CPU build · NumPy · Streamlit · "
     "tifffile/GeoTIFF.", 1, False, INK),
    ("LoFTR matcher (Apache-2.0) · MAGSAC++ · gradient-orientation illumination "
     "normalisation · FFT area check.", 1, False, INK),
    ("Data: Chandrayaan-2 OHRC, TMC-2, IIRS (PRADAN) · LRO NAC · Kaguya TC and MI "
     "· LOLA.", 1, False, INK),
    # "Runtime and match distribution": median seconds over the 74 deg S OHRC -> NAC windows.
    ("Hardware: a standard laptop, CPU only, no discrete GPU, fully offline; median 8.2 s per "
     "640-px window (89 OHRC → NAC windows).", 1, True, ACCENT),
]

S3_RIGHT = [
    ("Methodology and process", 0, True, BLUE),
    ("The flow above is the implemented pipeline, in the order it runs — every box is a "
     "function in the codebase, not a plan.", 1, False, INK),
        # The point of the diagram, said once. fig_pipeline draws six standard steps after the input
    # box, then the 8x8 coverage check (which DOES read match positions), then the area check
    # (which never does). "Six standard / eighth is ours" counts that way on purpose.
        ("Six of those steps are standard practice. The eighth box is ours: the only one that never "
     "reads a match position, and the only one allowed to overrule the rest. The 8×8 coverage "
     "check before it does read them — a different check doing a different job.",
     1, True, ACCENT),
    ("Working prototype today: hand it a pair and it returns the registered GeoTIFF, GDAL/QGIS "
     "control points, an ISIS match list, metrics and the trust map — on a laptop, offline.",
     1, False, INK),
]

S4 = [
    ("Analysis of the feasibility", 0, True, BLUE),
    # REPORT.md footer, verbatim: "177 registered pairs (160 distinct ground windows)". The two
    # are different counts and the slide must use the noun REPORT uses (claim-checker H1, v4).
    
    # "The whole lit overlap, tiled": windows, area, verdicts, held-out median of the accepted
    # and how many are under 3 px (the one that is not is the 316 px window, an inlier-ratio
    # limit of the metric - the deck must not imply 37/37 were all sub-pixel).
    ("The hardest honest test we could set: the whole lit, textured overlap of one OHRC frame "
     "with one NAC at 74 °S, tiled, nothing hand-picked — 37 windows, 13.1 km², 37/37 "
     "accepted, held-out median 0.61 px = 0.57 m on the 0.93 m NAC grid; 36 of 37 under 3 px, "
     "and the outlier (a low-inlier-ratio window the image evidence, NCC 0.87–0.95, says is "
     "registered) is printed, not averaged away.", 1, False, INK),
    # "Sub-pixel accuracy, with the pixel grid named": the synthetic row (0 / 15 deg) and the
    # loop row (px, m, grid). Each names its grid AND its metres (Invariant 2) and says what it
    # is measured against. Loops are consistency, NOT ground accuracy.
        ("Against exact truth (synthetic, LOLA-rendered) on the 60 m grid: 0.086 px = 5.1 m with "
     "the Suns 0–15° apart, degrading to 1.096 px = 65.8 m at 45°. Six three-image loops close "
     "to 0.107 m on the 1.245 m NAC grid — consistency, not accuracy, and labelled so.",
     1, False, INK),
    ("Potential challenges and risks", 0, True, ACCENT),
    # "MiLOI" table rows 90-120, 120-180 (all methods); "Real sun-angle sweep" bins 60-90,
    # 90-120. MiLOI's 90 deg is a SUN-VECTOR angle; every other Sun figure on the deck is an
    # azimuth difference, so it is named (claim-checker M4, v4).
    ("The hard band is the field's, not ours: none of the 16 MiLOI pairs with Sun vectors 90° "
     "or more apart registered under any method — ours, SIFT, ORB or AKAZE — and our sweep "
     "accepts 0 of 12 at 60–120° azimuth, and says so.", 1, False, INK),
    # "Real viewpoint: TMC-2 fore -> aft": held-out median. "... TC -> IIRS": verdict counts.
    # REPORT.md lines 143-152. The four OHRC -> TMC-2 windows are the strongest thing on this
    # slide once read the right way round: the matcher DID produce a fit on each (6-7 inliers at
    # 5-9 % coverage), and a fit like that reports a small in-sample residual by construction -
    # MAGSAC++ keeps only matches within threshold. The area check measured the alignment
    # not one cell of 64 verifiable, and contradicted all four. Refusing that is the product
    # working, and it is the standard a judge should hold every entry to. Said without naming
    # anyone. The held-out medians on these rows (112-268 px = 629-1,495 m) are deliberately
    # NOT quoted as "how wrong": at inlier ratios of 0.05-0.07 that statistic describes the
    # outliers, not the alignment (Known issue 1 - the 316 px tiled window is the same effect
    # on a correct alignment). The area check's own verdict is the defensible number.
        ("OHRC against TMC-2 nadir, Suns 120° apart: the matcher kept 6–7 inliers per window at "
     "5–9% coverage and fitted them to 0.13–0.96 px per axis — sub-pixel, by construction, on "
     "six points. Not one held-out match agreed with that fit. The area check could verify not "
     "one cell of 64, contradicted all four, and the system declared its fallback. Six points "
     "and their own residual are not a registration we ship; this check is what stops us.",
     1, True, ACCENT),
    ("Two more, named before a reviewer does: relief parallax is not a homography, so TMC-2 "
     "fore against aft accepts 1 window of 4; and IIRS against Kaguya TC at 12×, 89 m per "
     "pixel, does not register matched direct.", 1, False, INK),
    ("Strategies for overcoming these challenges", 0, True, BLUE),
    # ops/specs/day_24.md: the one TMC-2 pass over SAC's frame with the Sun near the OHRC's is
    # identified in PRADAN and is the next run. Its azimuth offset is NOT quoted here because it
    # is not in REPORT.md (Invariant 1); it goes on the slide the day it is measured.
    ("Next: the one TMC-2 pass over this frame with the Sun near the OHRC's, already identified "
     "in the archive; IIRS chained through TMC-2 at intermediate scale, not matched direct "
     "against TC at 12×; tile-level local transforms with LOLA orthorectification for relief. "
     "Each answers a measured failure, and the check that refused these grades the fixes.",
     1, False, INK),
]

S5 = [
    ("Potential impact on the target audience", 0, True, BLUE),
    ("Landing-site safety at the lunar south pole. A hazard map is only as good as the "
     "alignment beneath it — and today that alignment arrives as one number for a whole "
     "image. Ours arrives as a verdict for every region of it.", 1, True, ACCENT),
    # Verified verbatim against arxiv.org/html/2604.25208 on 22 Sep 2026, Section VI: "the
    # present framework focuses exclusively on radiometric normalization and does not address
    # geometric misalignment or parallax effects"; Section VII: "Future research will ...
    # explore hybrid frameworks that jointly address both geometric alignment and radiometric
    # harmonization." Authors overlap the PS-setters' paper. Cited on slide 6.
        ("It is the half SAC has named as missing. SAC's 2026 lunar-mosaic paper states that its "
     "framework \"focuses exclusively on radiometric normalization and does not address "
     "geometric misalignment or parallax effects\", and sets joint geometric "
     "and radiometric frameworks as future research (arXiv:2604.25208). This is the geometric "
     "half, with a verdict on every region — so mosaics and change detection can be gated per "
     "region.", 1, False, INK),
    # The rotation/scale table's "cells moved >2 px that are NOT verified" summary line: the
    # one impact figure a judge remembers, because it is the failure mode a frame verdict misses.
        ("Why per-region matters: a rotation about the centre leaves the centre still and moves "
     "the corners, so the frame verdict is the wrong thing to watch — at 3 m of corner "
     "displacement 0 of 120 trials contradict, and at 5 m, 105 of 120 still say \"good\". The "
     "8×8 map is what carries it: of the cells such an error displaces past 2 px on the "
     "reference grid (0.93–1.62 m per pixel here), 94% lose verified state.", 1, False, INK),
    ("Benefits of the solution", 0, True, ACCENT),
    ("Scientific: a verdict per region, calibrated on real lunar imagery (figure).",
     1, False, INK),
    ("Economic: open-source and CPU-only — no GPU purchase, no licence cost, and the "
     "outputs load in QGIS and GDAL today.", 1, False, INK),
    ("Sustainable: adding an instrument needs a loader, not a new pipeline. Public planetary "
     "data only, and it runs offline.", 1, False, INK),
]

S6 = [
    # First group on purpose. The portal takes only a PS, a title, a description and this PDF -
    # there is no link field - so this line is the ONLY route a judge has from the deck to the
    # code, the evidence or the report. Slide 6 is the one slide with room (Known issue 11).
    ("Code, evidence and the full report", 0, True, BLUE),
    ("github.com/samarthputhraya/sih26166 — the pipeline, the evidence logs, and REPORT.md, "
     "regenerated from them by one command", 1, False, ACCENT),
    # NOT "in REPORT.md at 7dd4e5b". The freeze MEASURED the rows at 7dd4e5b; REPORT.md was
    # regenerated from them afterwards and committed at be94774. At 7dd4e5b the report is the
    # previous one (generated from b678272) and trust_real_calibration.csv does not exist there
    # at all - so the trust figures on slides 2 and 5 are provably absent from it. A judge with
    # the repo URL from the bullet above can check that in fifteen seconds. Say "measured at".
        ("Every figure here is in REPORT.md. Real-pair rows measured at the freeze commit 7dd4e5b; "
     "MiLOI rows matched at e10deb0, scored at 7dd4e5b; REPORT.md regenerated at 3fa526b, no "
     "logged number changed",
     1, False, INK),
    ("Lunar domain", 0, True, BLUE),
    ("Makharia, Singla, Amitabh, Dube, Sharma — Space Applications Centre (ISRO) and Manipal "
     "University Jaipur, 2025 · arxiv.org/abs/2509.04775", 1, False, INK),
    ("Singh, Singla, Hemrajani, Dube, Amitabh, Patel — \"Towards Seamless Lunar Mosaics\", Space "
     "Applications Centre, 2026 · arxiv.org/abs/2604.25208", 1, False, INK),
    ("Xie, Liu, Di et al. — Remote Sensing 17(13):2302, 2025 (MiLOI dataset)", 1, False, INK),
    ("Methods we build on", 0, True, BLUE),
    ("LoFTR, detector-free local feature matching — Sun et al., CVPR 2021 · "
     "arxiv.org/abs/2104.00680", 1, False, INK),
    ("MAGSAC++ — Barath et al., CVPR 2020 · arxiv.org/abs/1912.05909", 1, False, INK),
    ("Reliability estimation — the basis of our contribution", 0, True, BLUE),
    ("Uss, Vozel, Lukin, Chehdi — IEEE TGRS 2016 · arxiv.org/abs/1602.02720", 1, False, INK),
    ("Brown & Lowe — IJCV 2007  ·  Wan, Shao, Li — 2021 · arxiv.org/abs/2106.12738", 1, False, INK),
    ("Truong et al., PDC-Net — CVPR 2021 · arxiv.org/abs/2101.01710", 1, False, INK),
    ("Data sources and licences", 0, True, BLUE),
    ("Chandrayaan-2 OHRC, TMC-2, IIRS — ISRO PRADAN (pradan.issdc.gov.in)  ·  LROC NAC, LOLA — "
     "NASA PDS, public domain", 1, False, INK),
    ("Kaguya TC and MI — JAXA SELENE archive  ·  MiLOI — github.com/Bin501/CNSFM (evaluation only)",
     1, False, INK),
]

# Per slide: text blocks (box, items, heading pt, body pt) and an optional figure
# (file, left, width). A side figure is centred vertically in the content band.
# fig3 (the stacked trust map) is drawn from two real pairs: SAC's OHRC->NAC w06 (accepted)
# above Kaguya TC->MI 1548 nm w01 (refused), re-cached by the freeze's report step.
SLIDES = {
    2: {"text": [(S2_COL, S2, 15, 11.5)],       # 11.5: the hard-Sun and multi-modal clauses (20 Sep) did not fit at 12
        "fig": ("fig3_trust_map.jpg",) + S2_FIG},
    # Body sizes dropped one notch on 3-6 (22 Sep) to pay for the claim-check additions: the
    # Sun-separation condition on the synthetic figure, the metres beside the multi-modal px,
    # the 316 px window, OHRC->TMC-2, and slide 6's three-clause provenance. Every one of those
    # is correctness, so they are not negotiable and the type is what gives.
    # Slide 3's columns were 1.95 in tall because the flow chart at 11.6 in wide is 3.03 in
    # tall and ended at 4.79. Narrowing it to 10.6 (2.77 in) and starting it at TOP frees
    # 0.33 in, which is three lines across the two columns.
    3: {"text": [((0.55, 4.62, 6.0, 2.28), S3_LEFT, 14, 11.5),
                 ((6.78, 4.62, 6.0, 2.28), S3_RIGHT, 14, 11.5)],
        "fig": ("fig4_pipeline.png", 1.365, 10.6), "fig_top": TOP},
    # Slide 4 is the densest. Narrowing its figure from 5.50 to 5.00 in gives the text column
    # 7.05 in instead of 6.55 - about 8 % more characters per line.
            4: {"text": [((0.55, TOP, 7.30, BOTTOM - TOP), S4, 14, 11)],
        "fig": ("fig5_real_sun_sweep.png", 8.00, 4.75)},
    5: {"text": [(LEFT_COL, S5, 15, 12.5)],
        "fig": ("fig6_trust_real_calibration.png",) + RIGHT_FIG},
    6: {"text": [(FULL, S6, 14, 12)]},
}


# The opening words of each content slide's pointer text, from the template.
POINTER_MARKERS = ("Proposed Solution", "Technologies to be used",
                   "Analysis of the feasibility", "Potential impact", "Details / Links")


def _pointer_box(slide):
    """The template's own pointer text box, identified by its text.

    It used to be "the widest text box that is not the title", which only works while the
    slide still holds nothing but template shapes. Our slide-6 content box is 12.23 in
    wide against the pointer box's 10.26 in, so anything calling this after the content is
    added picks the wrong box - which is exactly what the preview renderer did.
    """
    for sh in slide.shapes:
        if (sh.has_text_frame and not sh.is_placeholder
                and any(m in sh.text_frame.text for m in POINTER_MARKERS)):
            return sh
    return None


def _team_oval(slide):
    for sh in slide.shapes:
        if sh.has_text_frame and sh.text_frame.text.strip() == "Your Team Name":
            return sh
    return None


def _footer(slide):
    """The template's footer placeholder, which reads '@SIH Idea submission- Template'."""
    for sh in slide.shapes:
        if sh.has_text_frame and "Idea submission" in sh.text_frame.text:
            return sh
    return None


# Two template strings this build deliberately fills or clears. They are NOT pointer text:
# the pointers are the grey bullet prompts inside each content slide ("Proposed Solution
# (Describe your Idea/Solution/Prototype)", "Technologies to be used ...") and those are
# never touched - `_check_pointers` proves it on every run.
#
#   "Your Team Name"                  the oval IS a placeholder for the team name; filled.
#   "@SIH Idea submission- Template"  the footer; cleared, keeping the bar and page number.
#
# Evidence for clearing the footer, gathered 9 Sep 2026 from eight public SIH decks: every
# Grand Finale deck inspected had removed it (Cannon Crew 2024, GeoGuards 2025, Tech
# Pioneers 2025 - all image-only PDFs, checked by rendering the footer strip) and every
# deck that kept it was an internal-round submission (NeXora, Sehat Sathi, Team Niyati).
# It is boilerplate identifying the file as the blank template, and printing the word
# "Template" on a finished submission is worse than the near-zero risk of dropping it.
# To put it back, delete the `_footer` call in build().
TEMPLATE_STRINGS_WE_SET = ("Your Team Name", "Idea submission")


def _delete_slide(prs, index):
    xml_slides = prs.slides._sldIdLst
    slides = list(xml_slides)
    rId = slides[index].get(
        "{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id")
    prs.part.drop_rel(rId)
    xml_slides.remove(slides[index])


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def _set_run_font(run, name=BODY_FONT):
    """Name the font for the latin, East Asian and complex-script ranges of one run.

    `run.font.name` writes only <a:latin>. Leaving <a:ea>/<a:cs> to be inherited from a
    theme that declares them empty is what sent ° and × through East-Asian font linking.
    Element order inside <a:rPr> is fixed by the schema: latin, then ea, then cs.
    """
    run.font.name = name
    rPr = run._r.get_or_add_rPr()
    for tag in ("a:ea", "a:cs"):
        for el in list(rPr.findall(qn(tag))):
            rPr.remove(el)
    after = rPr.find(qn("a:latin"))
    for tag in ("a:ea", "a:cs"):
        el = rPr.makeelement(qn(tag), {"typeface": name})
        if after is not None:
            after.addnext(el)
        else:
            rPr.append(el)
        after = el


def _set_bullet(para, char, mar_l, indent):
    """A real PowerPoint bullet with a hanging indent, not a "•" typed into the text.

    A literal bullet gives no hanging indent, so the second and later lines of a wrapped
    bullet wrapped back under the bullet itself instead of under its first word - visible
    on every multi-line bullet in the 9 Sep build. marL/indent make the text hang.
    Schema order inside <a:pPr>: lnSpc, spcBef, spcAft, ... buFont, buChar/buNone, defRPr.
    """
    pPr = para._p.get_or_add_pPr()
    pPr.set("marL", str(int(Inches(mar_l))))
    pPr.set("indent", str(int(Inches(indent))))
    for tag in ("a:buNone", "a:buChar", "a:buAutoNum", "a:buFont"):
        for el in list(pPr.findall(qn(tag))):
            pPr.remove(el)
    new = ([pPr.makeelement(qn("a:buNone"), {})] if char is None
           else [pPr.makeelement(qn("a:buFont"), {"typeface": BODY_FONT}),
                 pPr.makeelement(qn("a:buChar"), {"char": char})])
    anchor = pPr.find(qn("a:defRPr"))
    for el in new:
        if anchor is not None:
            anchor.addprevious(el)
        else:
            pPr.append(el)


def _add_text(slide, box, items, head_pt, body_pt):
    left, top, width, height = box
    tb = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = tb.text_frame
    tf.word_wrap = True
    for i, (text, level, bold, colour) in enumerate(items):
        para = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        run = para.add_run()
        run.text = text
        run.font.bold = bold
        run.font.color.rgb = colour
        run.font.size = Pt(body_pt if level else head_pt)
        _set_run_font(run)
        # Headings sit flush left with no bullet; bullets hang by BULLET_INDENT.
        if level:
            _set_bullet(para, "•", BULLET_INDENT, -BULLET_INDENT)
        else:
            _set_bullet(para, None, 0.0, 0.0)
        para.line_spacing = 1.0
        para.space_before = Pt(6 if (level == 0 and i) else 2)
        para.space_after = Pt(2)
    return sum(len(t.split()) for t, _l, _b, _c in items)


def _add_fig(slide, spec, fig_top=None):
    name, left, width = spec
    path = FIGURES / name
    if not path.is_file():
        print(f"  !! figure missing: {path.name} - run `python -m presentation.make_figures`")
        return
    with Image.open(path) as im:
        w_px, h_px = im.size
    height = width * h_px / w_px
    if fig_top is None:                      # centre in the content band
        fig_top = TOP + max(0.0, (BOTTOM - TOP - height) / 2)
    slide.shapes.add_picture(str(path), Inches(left), Inches(fig_top), width=Inches(width))


# "multi-modal" and "cross-sensor" were banned for the college round, when no such real pair
# existed. Real visible<->infrared (Kaguya MI, IIRS) and OHRC<->NAC rows exist since 18 Sep, so
# the words are allowed - but never next to MiLOI or fore/aft, which are the SAME sensor
# (checked below, sentence by sentence; claim-checker checks the rest).
BANNED = ("<", "Your Team Name", "Idea submission", "62,519", "43.9", "0.7 px",
          "cross sensor", "SNPSU LunaX")          # the old team NAME; the ID is SNPSU0192
SAME_SENSOR_WORDS = ("MiLOI", "fore vs aft", "fore/aft", "NAC pairs")


def _audit_deck(deck) -> list[str]:
    """Everything about the built file that a machine can check, checked on every run.

    This exists because the deck was corrected one defect at a time over several rounds -
    template footer, off-canvas figure text, 4.5 pt chart labels, ° rendered through an
    East-Asian fallback, bullets with no hanging indent, an asymmetric right margin. Each
    was found by a human looking at a slide. Everything below is now found by the build.
    """
    bad: list[str] = []
    if len(deck.slides) != 6:
        bad.append(f"slide count is {len(deck.slides)}, must be 6 including the title page")

    band_l, band_r, band_b = 0.54, 12.79, 6.96
    for i, slide in enumerate(deck.slides, 1):
        ours = [sh for sh in slide.shapes
                if not sh.is_placeholder and sh.shape_type != 13
                and sh.has_text_frame and sh.text_frame.text.strip()
                and "Proposed Solution" not in sh.text_frame.text
                and "Technologies to be used" not in sh.text_frame.text
                and "Analysis of the feasibility" not in sh.text_frame.text
                and "Potential impact" not in sh.text_frame.text
                and "Details / Links" not in sh.text_frame.text
                and sh.text_frame.text.strip() != TEAM_NAME]
        pics = [sh for sh in slide.shapes if sh.shape_type == 13
                and Emu(sh.width).inches > 3]

        # Slide 1 is the template's own title layout - its metadata block sits at 0.36 in
        # and there is no footer bar - so the content band applies to slides 2-6 only.
        for sh in (ours + pics) if i > 1 else []:
            l, r = Emu(sh.left).inches, Emu(sh.left).inches + Emu(sh.width).inches
            b = Emu(sh.top).inches + Emu(sh.height).inches
            if l < band_l or r > band_r:
                bad.append(f"slide {i}: a shape spans {l:.2f}..{r:.2f} in, outside the "
                           f"{band_l:.2f}..{band_r:.2f} in content band")
            if b > band_b:
                bad.append(f"slide {i}: a shape reaches {b:.2f} in, into the footer bar")

        # A figure and a text box must not share space.
        for pic in pics:
            pl, pr = Emu(pic.left).inches, Emu(pic.left).inches + Emu(pic.width).inches
            pt_, pb = Emu(pic.top).inches, Emu(pic.top).inches + Emu(pic.height).inches
            for tb in ours:
                tl, tr = Emu(tb.left).inches, Emu(tb.left).inches + Emu(tb.width).inches
                tt, tb_ = Emu(tb.top).inches, Emu(tb.top).inches + Emu(tb.height).inches
                if pl < tr and tl < pr and pt_ < tb_ and tt < pb:
                    bad.append(f"slide {i}: figure and text box overlap")

        for sh in ours:
            ends = []
            for p in sh.text_frame.paragraphs:
                if not p.text.strip():
                    continue
                pPr = p._p.find(qn("a:pPr"))
                bulleted = pPr is not None and pPr.find(qn("a:buChar")) is not None
                if bulleted:
                    ends.append(p.text.rstrip().endswith("."))
                    mar_l = int(pPr.get("marL") or 0)
                    ind = int(pPr.get("indent") or 0)
                    if mar_l <= 0 or ind >= 0:
                        bad.append(f"slide {i}: a bullet has no hanging indent "
                                   f"(marL={mar_l}, indent={ind}); wrapped lines will sit "
                                   f"under the bullet")
                for r in p.runs:
                    rPr = r._r.find(qn("a:rPr"))
                    faces = {t: (rPr.find(qn(f"a:{t}")).get("typeface")
                                 if rPr is not None and rPr.find(qn(f"a:{t}")) is not None
                                 else None)
                             for t in ("latin", "ea", "cs")}
                    if set(faces.values()) != {BODY_FONT}:
                        bad.append(f"slide {i}: run {r.text[:28]!r} has fonts {faces} - a "
                                   f"missing ea/cs face sends ° and × through font linking")
            if len(set(ends)) > 1:
                bad.append(f"slide {i}: bullets in one box mix terminal full stops "
                           f"({sum(ends)} with, {len(ends) - sum(ends)} without)")

        text = " ".join(sh.text_frame.text for sh in slide.shapes if sh.has_text_frame)
        for word in BANNED:
            if word in text:
                bad.append(f"slide {i}: banned text {word!r} is on the slide")
        # Invariant 2: a same-sensor pair (MiLOI, TMC-2 fore/aft) is never cross-sensor or
        # multi-modal. Checked per sentence, so "same-sensor NAC pairs (MiLOI)" passes and
        # "cross-sensor MiLOI pairs" does not.
        for sent in re.split(r"(?<=[.;])\s+", text):
            if any(w in sent for w in SAME_SENSOR_WORDS) and re.search(
                    r"cross-sensor|multi-modal", sent, re.I):
                bad.append(f"slide {i}: same-sensor pair called cross-sensor/multi-modal: "
                           f"{sent[:60]!r}")
        # Provenance. "in REPORT.md AT commit X" says X's tree contains a report holding these
        # figures; the freeze commit's tree does not - it carries the PREVIOUS report, and the
        # trust CSV is not in it at all. The rows were MEASURED at the freeze and the report was
        # regenerated afterwards. This shipped once, on slide 6, next to the repository URL that
        # lets a judge check it. Verify the claim if it is made, rather than banning the words.
        for m in re.finditer(r"REPORT\.md[^.]{0,40}?at\s+(?:the\s+\w+[- ]\w+\s+)?commit\s+"
                             r"`?([0-9a-f]{7,40})`?", text, re.I):
            sha = m.group(1)
            got = subprocess.run(["git", "show", f"{sha}:REPORT.md"],
                                 cwd=str(HERE.parent), capture_output=True, text=True)
            missing = [f for f in ("13.1 km", "0.57 m", "8.2 s", "160 distinct")
                       if f not in got.stdout]
            if got.returncode or missing:
                bad.append(f"slide {i}: claims its figures are in REPORT.md at commit {sha}, "
                           f"but that commit's REPORT.md is missing {missing or 'itself'}. "
                           f"Say 'measured at' - the report is regenerated after the freeze")
        n_tbd = text.count("TBD")
        if n_tbd:
            bad.append(f"slide {i}: {n_tbd} [TBD] placeholder(s) - fill from the freeze commit")

    all_text = " ".join(sh.text_frame.text for s in deck.slides for sh in s.shapes
                        if sh.has_text_frame)
    for need in (TEAM_ID, TEAM_NAME, "SIH26166"):
        if need not in all_text:
            bad.append(f"{need!r} does not appear anywhere in the deck")
    return bad


def _check_pointers(template, deck) -> bool:
    """Every pointer text on every content slide must survive unchanged (whitespace aside)."""
    ok = True
    for i in range(1, 6):
        want = [_norm(sh.text_frame.text) for sh in template.slides[i].shapes
                if sh.has_text_frame and sh.text_frame.text.strip()
                and not any(s in sh.text_frame.text for s in TEMPLATE_STRINGS_WE_SET)]
        have = [_norm(sh.text_frame.text) for sh in deck.slides[i].shapes if sh.has_text_frame]
        for w in want:
            if w not in have:
                print(f"  !! slide {i + 1}: template text altered or missing: {w[:70]!r}")
                ok = False
    return ok


def build() -> int:
    if not TEMPLATE.exists():
        print(f"missing {TEMPLATE} - download the official template first")
        return 2
    prs = Presentation(str(TEMPLATE))

    # ---- slide 1: the metadata block, keeping the template's own labels ----
    s1 = prs.slides[0]
    meta = None
    for sh in s1.shapes:
        if sh.has_text_frame and "Problem Statement ID" in sh.text_frame.text:
            meta = sh
            break
    if meta is not None:
        tf = meta.text_frame
        tf.clear()
        for i, (label, value) in enumerate(TITLE_META):
            para = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            _set_bullet(para, None, 0.0, 0.0)
            r1 = para.add_run()
            r1.text = f"{label} "
            r1.font.size = Pt(15)
            r1.font.bold = True
            r1.font.color.rgb = MUTED
            _set_run_font(r1)
            r2 = para.add_run()
            r2.text = value
            r2.font.size = Pt(15)
            r2.font.bold = False
            r2.font.color.rgb = INK
            _set_run_font(r2)
            para.space_after = Pt(8)

    # The title page is the first thing a judge reads and the template leaves it as a form.
    # The metadata block runs y 2.27 to roughly 4.6 in; the footer bar starts at 6.95. One
    # line of thesis goes in that gap, so the deck states what it is before it states what
    # it measured. This adds a NEW text box - no pointer text exists on slide 1 to touch.
    _add_text(s1, TITLE_LINE_BOX, TITLE_LINE, 20, 12.5)
    for _para in list(s1.shapes)[-1].text_frame.paragraphs[1:]:
        _set_bullet(_para, None, 0.0, 0.0)

    # ---- content slides ----
    words = {}
    for idx, spec in SLIDES.items():
        slide = prs.slides[idx - 1]

        # The template's oval is a placeholder for the team name; fill it, keep its style.
        oval = _team_oval(slide)
        if oval is not None:
            paras = oval.text_frame.paragraphs
            first = paras[0]
            if first.runs:
                first.runs[0].text = TEAM_NAME
                _set_run_font(first.runs[0])
                for r in first.runs[1:]:
                    r.text = ""
            else:
                first.text = TEAM_NAME
            for p in paras[1:]:
                p._p.getparent().remove(p._p)

        # Clear the "@SIH Idea submission- Template" footer; the bar and page number stay.
        ft = _footer(slide)
        if ft is not None:
            ft.text_frame.clear()
            ft.text_frame.paragraphs[0].add_run().text = ""

        # Move the official pointer text under the title bar, small and grey. TEXT UNCHANGED.
        pb = _pointer_box(slide)
        if pb is not None:
            pb.left, pb.top = Inches(POINTER_BOX[0]), Inches(POINTER_BOX[1])
            pb.width, pb.height = Inches(POINTER_BOX[2]), Inches(POINTER_BOX[3])
            tfp = pb.text_frame
            tfp.word_wrap = True
            try:
                tfp.auto_size = None
            except Exception:
                pass
            # Slide 2's pointer box carries two EMPTY paragraphs sized 32 pt that alone open
            # an 80 px hole. They carry no pointer text, so removing them changes no pointer;
            # only whitespace goes. `_check_pointers` compares whitespace-normalised text.
            for para in list(tfp.paragraphs):
                if not para.text.strip():
                    para._p.getparent().remove(para._p)
            for para in tfp.paragraphs:
                para.space_before = Pt(0)
                para.space_after = Pt(0)
                para.line_spacing = 0.85
                para.font.size = Pt(8)
                para.font.italic = True
                para.font.color.rgb = MUTED
                for run in para.runs:
                    run.font.size = Pt(8)
                    run.font.italic = True
                    run.font.bold = False
                    run.font.color.rgb = MUTED

        if "fig" in spec:
            _add_fig(slide, spec["fig"], spec.get("fig_top"))
        words[idx] = sum(_add_text(slide, box, items, hp, bp)
                         for box, items, hp, bp in spec["text"])

    _delete_slide(prs, 6)          # the instructions slide, which itself says we may
    prs.save(str(OUT))

    deck = Presentation(str(OUT))
    pointers_ok = _check_pointers(Presentation(str(TEMPLATE)), deck)
    problems = _audit_deck(deck)
    print(f"  wrote {OUT.name}  ({OUT.stat().st_size:,} bytes, {len(deck.slides)} slides)")
    print("  words of ours per slide: " + " · ".join(f"s{k}={v}" for k, v in sorted(words.items())))
    print(f"  pointer text unchanged on every content slide: {'YES' if pointers_ok else 'NO'}")
    if problems:
        print(f"  AUDIT: {len(problems)} problem(s)")
        for line in problems:
            print(f"    !! {line}")
    else:
        print("  AUDIT: clean - geometry, fonts, bullets, punctuation, banned terms")
    print("  NEXT: export to PDF - the portal accepts PDF only, not .pptx")
    print("        PowerPoint: File > Save As > PDF   (or Print > Microsoft Print to PDF)")
    return 0 if (pointers_ok and not problems) else 1


if __name__ == "__main__":
    raise SystemExit(build())
