"""Build the SIH26166 deck into the official template, from the content in this folder.

    python -m presentation.build_deck

Inputs   presentation/sih_template.pptx   (924,505 bytes, sha256 ce3e5dee...)
         presentation/figures/*.png       (generated by presentation.make_figures)
Output   presentation/SIH26166_LunaXX_deck.pptx   (national round, v2 - 19 Sep 2026)

V2 (NATIONAL ROUND). The text below is rebuilt around the real-data evidence of 18-19 Sep
(REPORT.md). Every number on a slide was copied from REPORT.md at the evidence-freeze commit
49bdad9 (FROZEN 20 Sep 00:36; evidence commit 36de5f4), and the comment beside it names the
REPORT.md section it came from. A new freeze means re-reading every one of them. The audit
still counts "TBD": the Team ID stays a placeholder until it is read off the portal. The college-round
deck (SIH26166_deck.pptx, built by this file up to 1864ad3) is not overwritten.

WHAT THE OFFICIAL INSTRUCTIONS SLIDE ACTUALLY SAYS, and how each line is honoured here:

  "Kindly keep the maximum slides limit up to six (6). (Including the title slide)"
      -> we ship exactly 6. The instructions slide (7) is deleted, which that slide
         explicitly permits.
  "Try to avoid paragraphs and post your idea in points /diagrams /Infographics /pictures"
      -> every content block is bullets, and every content slide carries a generated
         figure: the trust map itself (2), the pipeline flowchart (3), the sun-angle
         curve (4), the calibration curve (5).
  "You can only use provided template ... without changing the idea details pointers
   (mentioned in previous slides)."
      -> THE POINTER TEXT IS NEVER EDITED. Not one character. It is moved under the
         title bar and set small and grey so it reads as the section guide it is, and
         our content goes in NEW text boxes below it. Moving a box does not change a
         pointer; rewriting it would. This is the conservative reading and it is the one
         we take, because the cost of being wrong is disqualification. The build checks
         this itself at the end of a run (see `_check_pointers`).
  "You need to save the file in PDF and upload the same on portal."
      -> the .pptx is the source; export to PDF before uploading. See the note printed
         at the end of a run.

Layout facts of the template that this file works around (measured with python-pptx):
  slide 13.33 x 7.5 in · "Your Team Name" oval at (0.36, 0.28) 1.37 x 0.88 in · title
  placeholder spans y -0.05..1.20 · SIH logo at (10.70, 0) 2.46 x 1.16 in · footer bar
  from y 6.95. The 4 Sep build put the pointers at y 1.06 and they printed straight
  through the oval on every content slide; they now start at y 1.20, below both.

Every number that appears on a slide is in the evidence logs (evaluation/*.csv, rendered by
ops/make_report.py into REPORT.md), or is a documented instrument/literature fact. The v2 audit
table is presentation/DECK_V2_DRAFT.md (DECK_CONTENT.md is the college round's). This file is
the only place deck prose lives in code - if a figure changes, re-run make_figures; if a number
changes, fix it here and in DECK_V2_DRAFT.md and re-run.

Audience (national round): SAC-ISRO image-processing scientists reading the PDF cold, ranking
it against every other SIH26166 idea. Novelty is 25 % of the college rubric; the national one
is not published. What they can check in ten seconds: the pair IDs from their own paper
(arXiv:2509.04775, Table 1), and whether "cross-sensor" / "multi-modal" / "sub-pixel" are used
the way Invariant 2 defines them.
"""
from __future__ import annotations

import pathlib
import re
import sys

from PIL import Image
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.oxml.ns import qn
from pptx.util import Emu, Inches, Pt

HERE = pathlib.Path(__file__).resolve().parent
TEMPLATE = HERE / "sih_template.pptx"
FIGURES = HERE / "figures"
OUT = HERE / "SIH26166_LunaXX_deck.pptx"

INK = RGBColor(0x1A, 0x1A, 0x1A)
MUTED = RGBColor(0x60, 0x60, 0x60)
BLUE = RGBColor(0x1F, 0x5C, 0xA8)
ACCENT = RGBColor(0xC2, 0x4A, 0x1E)

# EVERY run we write names this font for latin, East Asian AND complex-script ranges.
#
# The template's theme declares <a:latin typeface="Calibri"/> but leaves <a:ea/> and
# <a:cs/> EMPTY. A run that inherits that has no font for any glyph PowerPoint classifies
# outside the latin range, so it resolves ° and × through font linking to a system East
# Asian face with full-width metrics - which is why the 9 Sep build rendered
# "at a 15°   sun difference" and "2.88 ×  better", with gaps we never typed. Calibri
# carries every character this deck uses (° × ± → ↔ ≤ — – ·), so naming it in all three
# ranges removes the fallback entirely.
BODY_FONT = "Calibri"

# National-round portal values. The team name on the portal is LunaXX (nominated 18 Sep; the
# 2026 guidelines forbid the institute's name in a team name - the college-round deck said
# "SNPSU LunaX"). The national Team ID's exact format is still an open question (STATUS, Open
# questions 1): it stays a placeholder, which the audit reports, until it is read off the portal.
TEAM_ID = "[TBD - portal Team ID]"
TEAM_NAME = "LunaXX"

# Labels copied from the template's own title block, separator included, rather than
# reworded with colons: the template writes "Problem Statement ID –", "Theme-",
# "Team Name (Registered on portal)". Only the values after them are ours.
TITLE_META = [
    ("Problem Statement ID –", "SIH26166"),
    ("Problem Statement Title-", "Multi-modal, Sun angle and scale invariant image "
                                 "correspondence using Chandrayaan-2 optical images "
                                 "(OHRC, TMC and IIRS)"),
    ("Theme-", "Space Technology"),
    ("PS Category-", "Software"),
    ("Team ID-", TEAM_ID),
    ("Team Name (Registered on portal)-", TEAM_NAME),
]

# Geometry (inches). Content sits under the pointer box, above the footer bar. The right
# margin matches the left one: 0.55 in each side, so the content band is 0.55..12.78. The
# 9 Sep build put side figures at 7.45 + 5.50 = 12.95, leaving 0.38 in on the right against
# 0.55 in on the left - a visible asymmetry against the template's centred title.
POINTER_BOX = (0.55, 1.24, 12.2, 0.44)   # below the oval (ends 1.16) and the title text
# The pointer box's four-line worst case (slide 2, 8 pt) ends at 1.68; the footer bar
# starts at 6.95. TOP/BOTTOM take the rest, which is what keeps slide 4 - the densest -
# off its ceiling.
TOP, BOTTOM = 1.74, 6.90
LEFT_COL = (0.55, TOP, 6.55, BOTTOM - TOP)          # text column beside a figure
RIGHT_FIG = (7.28, 5.50)                            # (left, width) of a side figure
# Slide 2 answers FOUR pointers where slides 4 and 5 answer three and two, so its figure
# is the STACKED trust map (5.0 x 7.2 in canvas): narrow and tall, which leaves the text
# 8.33 in instead of 6.55 and still lands every label above the 6 pt on-slide floor.
S2_COL = (0.55, TOP, 8.33, BOTTOM - TOP)
S2_FIG = (9.18, 3.60)
FULL = (0.55, TOP, 12.23, BOTTOM - TOP)
BULLET_INDENT = 0.26                                # hanging indent for wrapped bullets

# (text, level, bold, colour). Level 0 is a heading, 1 a bullet.
#
# EVERY HEADING IS ONE OF THE TEMPLATE'S OWN POINTERS, in the template's order.
#
# The 9 Sep build used headings we invented — "The finding, not the feature", "Risks -
# stated by us, with numbers", "Built, tested, usable", "Trust as a deliverable". They read
# as commentary on our own work rather than as answers, which is what makes a deck feel
# machine-written; worse, slide 2 never answered "Detailed explanation of the proposed
# solution" at all, because the how-it-works had been left on slide 3. Round 1 is screened
# from the file with nobody presenting, so an evaluator reads down the grey pointers and
# looks for each one in turn. Each is now a heading directly beneath them.
# V2 CONTENT. Every number was filled at the evidence freeze (49bdad9) from the source in its comment
# (REPORT.md section names are the headings `python -m ops.make_report` writes). Invariant 2:
# OHRC<->NAC / OHRC<->TC are cross-sensor AND cross-mission; OHRC<->TMC-2 is cross-sensor, same
# mission; NAC<->NAC (MiLOI, the sweep's NAC legs) and TMC-2 fore<->aft are SAME sensor; only
# visible<->infrared (MI, IIRS) and optical<->elevation (LOLA) are multi-modal.
S2 = [
    ("Proposed Solution", 0, True, BLUE),
    ("A lunar image-registration engine that knows when it is wrong: it aligns Chandrayaan-2 "
     "imagery to lunar references across Sun angle, scale and sensor, and reports region by "
     "region whether it can be trusted.", 1, False, INK),
    ("Detailed explanation", 0, True, BLUE),
    # core/pipeline.run_all order: LoFTR -> _refine_subpixel -> filter_matches (MAGSAC++).
    ("One ground scale; lighting reduced to edge direction; LoFTR matches; sub-pixel "
     "refinement; MAGSAC++.", 1, False, INK),
    ("An independent area check, blind to match positions, cross-correlates the warped image "
     "with the reference in 8×8 cells: agrees, unconfirmed, or contradicted, which falls back.",
     1, False, INK),
    ("How it addresses the problem", 0, True, BLUE),
    # REPORT.md "SAC's own benchmark pair (equatorial ...)": Δsun az (an AZIMUTH difference),
    # count of `agrees` / rows. "(polar ...)": `agrees` / rows.
    ("SAC's own pairs (arXiv:2509.04775, Table 1), cross-sensor: OHRC ↔ NAC M1350459544RE, "
     "Sun azimuths 174° apart, 6/6 windows accepted; polar M165491149RE, 132°, 4/6, the "
     "other two flagged.", 1, False, INK),
    # "Real sun-angle sweep": "All bins" line (NAC frames, azimuth range).
    # "Scale rung: ... TC ortho map": scale column, `agrees` / rows. LOLA: "Declared-failure rung".
    # Polar: 4 agrees, 1 unconfirmed, 1 contradicted (fallback) = "the other two flagged".
    ("Sun: one OHRC frame vs 25 NAC frames, azimuths 3–153° apart. Scale: to NAC ~1 m "
     "and Kaguya TC 7.4 m (29.6×, 3/4 accepted); to LOLA 60 m it declares failure.",
     1, False, INK),
    # "Kaguya TC -> Kaguya MI" + "... IIRS": windows declared fft fallback / total.
    ("Multi-modal: Kaguya TC (visible) to Kaguya MI 1548 nm and Chandrayaan-2 IIRS infrared — "
     "learned matching fails; "
     "13 of 14 windows are refused and fall back, the other stays unconfirmed.", 1, False, INK),
    ("Innovation and uniqueness", 0, True, ACCENT),
    # "MiLOI": the verdict table, column "matcher H within 3 px" (what the trust layer judges).
    # NOT "independent": the truth network is built from OTHER pairs where ours and SIFT agree.
    ("MiLOI, 81 real same-sensor NAC pairs, truth from other pairs where ours and SIFT agree "
     "(56 in scene S3, where it has no redundancy): agrees within 3 px 33/33, contradicted "
     "wrong 43/43, unconfirmed wrong 5/5.", 1, False, INK),
    # "Trust layer on real imagery: planted ...": 0 m row = false alarms; 3 m row; >= 5 m rows.
    ("Planted wrong answers, 22 real OHRC/NAC windows (Sun azimuths under 10° apart): 0/44 "
     "false alarms; flagged 81% at 3 m, 100% from 5 m, 2/352 at 1–2 m. No matches means "
     "\"no evidence\", never \"verified\".", 1, True, ACCENT),
]

S3_LEFT = [
    ("Technologies to be used", 0, True, BLUE),
    ("Python · OpenCV · PyTorch, CPU build · NumPy · Streamlit · tifffile/GeoTIFF.", 1, False, INK),
    ("LoFTR matcher (Apache-2.0) · MAGSAC++ · gradient-orientation illumination "
     "normalisation · FFT area check.", 1, False, INK),
    ("Data: Chandrayaan-2 OHRC, TMC-2, IIRS (PRADAN) · LRO NAC · Kaguya TC and MI · LOLA.",
     1, False, INK),
    ("Hardware: a standard laptop, CPU only, no discrete GPU, fully offline.", 1, True, ACCENT),
]

S3_RIGHT = [
    ("Methodology and process", 0, True, BLUE),
    ("The flow above is the implemented pipeline, in the order it runs — every box is a "
     "function in the codebase, not a plan.", 1, False, INK),
    ("Prototype: a Streamlit app exporting the registered GeoTIFF, GDAL/QGIS control points, "
     "an ISIS-style match list, metrics and the trust map.", 1, False, INK),
    ("Every run appends to the evidence logs; a generator rebuilds the report from them, and "
     "every number here traces to it.", 1, False, INK),
]

S4 = [
    ("Analysis of the feasibility", 0, True, BLUE),
    # REPORT.md footer: registered pairs; instrument pairings = its pair sections (OHRC-NAC,
    # NAC-NAC, OHRC-TMC2, TMC2-TMC2, TC-MI, TC-IIRS, OHRC-TC, OHRC-LOLA). "Loop closure".
    ("Built and measured, not proposed: 136 real window pairs, 8 instrument pairings, public "
     "data, open-source libraries. Six three-image loops close to a median 0.10 m "
     "(consistency, not ground accuracy).", 1, False, INK),
    # "Chandrayaan-2 OHRC -> LRO NAC": held-out median range, Δsun az range, ref_gsd_m values.
    ("Held-out residual, OHRC → NAC, median per window: 0.41–1.0 px (0.51–0.94 m) at 74 °S, "
     "Sun azimuths 3–6° apart, ~1 m grids; 0.69–1.7 px (1.1–2.7 m) on SAC's equatorial pair, "
     "174° apart, 1.62 m grid. Not ground truth.",
     1, False, INK),
    ("Potential challenges and risks", 0, True, ACCENT),
    # "MiLOI" table rows 90-120, 120-180 (all methods); "Real sun-angle sweep" bins 60-90, 90-120
    # (accepted / windows) and 120-180. "SAC's benchmark site: OHRC -> TMC-2": Δsun az, verdicts.
    ("The hard band: no method registered any of the 16 MiLOI pairs with Suns over 90° apart "
     "(all scene S3); our sweep accepted 0 of 12 at 60–120° azimuth, 10 of 15 at 120–153°; "
     "OHRC → TMC-2 at SAC's site (azimuths 120°, incidence 59° apart): all 4 refused.",
     1, False, INK),
    # "SAC's own benchmark pair (equatorial ...)" note: the wide-search offset.
    ("Archive geometry is not truth: at SAC's equatorial site the NAC's published corners and "
     "the OHRC grid disagree by 1.9 km; a wide search removes it before matching.", 1, False, INK),
    # "Real viewpoint: TMC-2 fore -> aft": held-out median column (NOT the RMSE-within-3-px one).
    ("Relief parallax is not a homography: TMC-2 fore vs aft (same sensor, same Sun) accepts 1 "
     "window of 4, held-out median 2.6 px (16 m) on its 5.9 m grid.", 1, False, INK),
    ("Strategies for overcoming these challenges", 0, True, BLUE),
    ("Tile-level local transforms and LOLA-based orthorectification for relief.", 1, False, INK),
    ("Full-scene tiled processing of OHRC strips; IIRS band selection for the infrared leg.",
     1, False, INK),
]

S5 = [
    ("Potential impact on the target audience", 0, True, BLUE),
    # "Trust layer on real imagery": >= 5 m rows; the 1-2 m rows are the stated floor.
    ("Landing-site safety at the lunar south pole: a hazard map is only as good as the "
     "alignment beneath it. Every region carries its own verdict; planted errors of 5 m or more "
     "were all flagged, 81% at 3 m, and at 2 m or less almost none — that floor is stated, "
     "not hidden.", 1, False, INK),
    # distinct OHRC products in real_pairs_log (source_product ch2_ohr_*) and their sites.
    ("OHRC frames co-register with LRO NAC (3 frames at 3 sites) and Kaguya TC (1 site) so far: "
     "mosaics, time series and change detection gated by trust.", 1, False, INK),
    ("Benefits of the solution", 0, True, ACCENT),
    ("Scientific: a verdict per region instead of one number for a whole image, calibrated "
     "on real imagery (figure).", 1, False, INK),
    ("Economic: open-source and CPU-only. No GPU purchase, no licence cost; outputs load in "
     "QGIS and GDAL today.", 1, False, INK),
    ("Security and privacy: public planetary data only, no personal data, fully offline.",
     1, False, INK),
    ("Sustainable and reusable: adding an instrument needs a loader, not a new pipeline.",
     1, False, INK),
]

S6 = [
    ("Lunar domain", 0, True, BLUE),
    ("Makharia, Singla, Amitabh, Dube, Sharma — Space Applications Centre (ISRO) and Manipal "
     "University Jaipur, 2025 · arxiv.org/abs/2509.04775", 1, False, INK),
    ("Singh, Singla, Hemrajani, Dube, Amitabh, Patel — \"Towards Seamless Lunar Mosaics\", Space "
     "Applications Centre, 2026 · arxiv.org/abs/2604.25208", 1, False, INK),
    ("Xie, Liu, Di et al. — Remote Sensing 17(13):2302, 2025 (MiLOI dataset)", 1, False, INK),
    ("Methods we build on", 0, True, BLUE),
    ("LoFTR, detector-free local feature matching — Sun et al., CVPR 2021 · "
     "arxiv.org/abs/2104.00680", 1, False, INK),
    ("MAGSAC++ — Barath et al., CVPR 2020 · arxiv.org/abs/1912.05909", 1, False, INK),
    ("Reliability estimation — the basis of our contribution", 0, True, BLUE),
    ("Uss, Vozel, Lukin, Chehdi — IEEE TGRS 2016 · arxiv.org/abs/1602.02720", 1, False, INK),
    ("Brown & Lowe — IJCV 2007  ·  Wan, Shao, Li — 2021 · arxiv.org/abs/2106.12738", 1, False, INK),
    ("Truong et al., PDC-Net — CVPR 2021 · arxiv.org/abs/2101.01710", 1, False, INK),
    ("Data sources and licences", 0, True, BLUE),
    ("Chandrayaan-2 OHRC, TMC-2, IIRS — ISRO PRADAN (pradan.issdc.gov.in)  ·  LROC NAC, LOLA — "
     "NASA PDS, public domain", 1, False, INK),
    ("Kaguya TC and MI — JAXA SELENE archive  ·  MiLOI — github.com/Bin501/CNSFM (evaluation only)",
     1, False, INK),
]

# Per slide: text blocks (box, items, heading pt, body pt) and an optional figure
# (file, left, width). A side figure is centred vertically in the content band.
# fig3 (the stacked trust map) is drawn from two real pairs: SAC's OHRC->NAC w06 (accepted)
# above Kaguya TC->MI 1548 nm w01 (refused), re-cached by the freeze's report step.
SLIDES = {
    2: {"text": [(S2_COL, S2, 15, 12.5)],
        "fig": ("fig3_trust_map.jpg",) + S2_FIG},
    3: {"text": [((0.55, 4.92, 6.0, 1.95), S3_LEFT, 15, 13),
                 ((6.78, 4.92, 6.0, 1.95), S3_RIGHT, 15, 13)],
        "fig": ("fig4_pipeline.png", 0.87, 11.6), "fig_top": 1.76},
    4: {"text": [(LEFT_COL, S4, 15, 13)],
        "fig": ("fig5_real_sun_sweep.png",) + RIGHT_FIG},
    5: {"text": [(LEFT_COL, S5, 16, 13.5)],
        "fig": ("fig6_trust_real_calibration.png",) + RIGHT_FIG},
    6: {"text": [(FULL, S6, 15, 13)]},
}


# The opening words of each content slide's pointer text, from the template.
POINTER_MARKERS = ("Proposed Solution", "Technologies to be used",
                   "Analysis of the feasibility", "Potential impact", "Details / Links")


def _pointer_box(slide):
    """The template's own pointer text box, identified by its text.

    It used to be "the widest text box that is not the title", which only works while the
    slide still holds nothing but template shapes. Our slide-6 content box is 12.23 in
    wide against the pointer box's 10.26 in, so anything calling this after the content is
    added picks the wrong box - which is exactly what the preview renderer did.
    """
    for sh in slide.shapes:
        if (sh.has_text_frame and not sh.is_placeholder
                and any(m in sh.text_frame.text for m in POINTER_MARKERS)):
            return sh
    return None


def _team_oval(slide):
    for sh in slide.shapes:
        if sh.has_text_frame and sh.text_frame.text.strip() == "Your Team Name":
            return sh
    return None


def _footer(slide):
    """The template's footer placeholder, which reads '@SIH Idea submission- Template'."""
    for sh in slide.shapes:
        if sh.has_text_frame and "Idea submission" in sh.text_frame.text:
            return sh
    return None


# Two template strings this build deliberately fills or clears. They are NOT pointer text:
# the pointers are the grey bullet prompts inside each content slide ("Proposed Solution
# (Describe your Idea/Solution/Prototype)", "Technologies to be used ...") and those are
# never touched - `_check_pointers` proves it on every run.
#
#   "Your Team Name"                  the oval IS a placeholder for the team name; filled.
#   "@SIH Idea submission- Template"  the footer; cleared, keeping the bar and page number.
#
# Evidence for clearing the footer, gathered 9 Sep 2026 from eight public SIH decks: every
# Grand Finale deck inspected had removed it (Cannon Crew 2024, GeoGuards 2025, Tech
# Pioneers 2025 - all image-only PDFs, checked by rendering the footer strip) and every
# deck that kept it was an internal-round submission (NeXora, Sehat Sathi, Team Niyati).
# It is boilerplate identifying the file as the blank template, and printing the word
# "Template" on a finished submission is worse than the near-zero risk of dropping it.
# To put it back, delete the `_footer` call in build().
TEMPLATE_STRINGS_WE_SET = ("Your Team Name", "Idea submission")


def _delete_slide(prs, index):
    xml_slides = prs.slides._sldIdLst
    slides = list(xml_slides)
    rId = slides[index].get(
        "{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id")
    prs.part.drop_rel(rId)
    xml_slides.remove(slides[index])


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def _set_run_font(run, name=BODY_FONT):
    """Name the font for the latin, East Asian and complex-script ranges of one run.

    `run.font.name` writes only <a:latin>. Leaving <a:ea>/<a:cs> to be inherited from a
    theme that declares them empty is what sent ° and × through East-Asian font linking.
    Element order inside <a:rPr> is fixed by the schema: latin, then ea, then cs.
    """
    run.font.name = name
    rPr = run._r.get_or_add_rPr()
    for tag in ("a:ea", "a:cs"):
        for el in list(rPr.findall(qn(tag))):
            rPr.remove(el)
    after = rPr.find(qn("a:latin"))
    for tag in ("a:ea", "a:cs"):
        el = rPr.makeelement(qn(tag), {"typeface": name})
        if after is not None:
            after.addnext(el)
        else:
            rPr.append(el)
        after = el


def _set_bullet(para, char, mar_l, indent):
    """A real PowerPoint bullet with a hanging indent, not a "•" typed into the text.

    A literal bullet gives no hanging indent, so the second and later lines of a wrapped
    bullet wrapped back under the bullet itself instead of under its first word - visible
    on every multi-line bullet in the 9 Sep build. marL/indent make the text hang.
    Schema order inside <a:pPr>: lnSpc, spcBef, spcAft, ... buFont, buChar/buNone, defRPr.
    """
    pPr = para._p.get_or_add_pPr()
    pPr.set("marL", str(int(Inches(mar_l))))
    pPr.set("indent", str(int(Inches(indent))))
    for tag in ("a:buNone", "a:buChar", "a:buAutoNum", "a:buFont"):
        for el in list(pPr.findall(qn(tag))):
            pPr.remove(el)
    new = ([pPr.makeelement(qn("a:buNone"), {})] if char is None
           else [pPr.makeelement(qn("a:buFont"), {"typeface": BODY_FONT}),
                 pPr.makeelement(qn("a:buChar"), {"char": char})])
    anchor = pPr.find(qn("a:defRPr"))
    for el in new:
        if anchor is not None:
            anchor.addprevious(el)
        else:
            pPr.append(el)


def _add_text(slide, box, items, head_pt, body_pt):
    left, top, width, height = box
    tb = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = tb.text_frame
    tf.word_wrap = True
    for i, (text, level, bold, colour) in enumerate(items):
        para = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        run = para.add_run()
        run.text = text
        run.font.bold = bold
        run.font.color.rgb = colour
        run.font.size = Pt(body_pt if level else head_pt)
        _set_run_font(run)
        # Headings sit flush left with no bullet; bullets hang by BULLET_INDENT.
        if level:
            _set_bullet(para, "•", BULLET_INDENT, -BULLET_INDENT)
        else:
            _set_bullet(para, None, 0.0, 0.0)
        para.line_spacing = 1.0
        para.space_before = Pt(6 if (level == 0 and i) else 2)
        para.space_after = Pt(2)
    return sum(len(t.split()) for t, _l, _b, _c in items)


def _add_fig(slide, spec, fig_top=None):
    name, left, width = spec
    path = FIGURES / name
    if not path.is_file():
        print(f"  !! figure missing: {path.name} - run `python -m presentation.make_figures`")
        return
    with Image.open(path) as im:
        w_px, h_px = im.size
    height = width * h_px / w_px
    if fig_top is None:                      # centre in the content band
        fig_top = TOP + max(0.0, (BOTTOM - TOP - height) / 2)
    slide.shapes.add_picture(str(path), Inches(left), Inches(fig_top), width=Inches(width))


# "multi-modal" and "cross-sensor" were banned for the college round, when no such real pair
# existed. Real visible<->infrared (Kaguya MI, IIRS) and OHRC<->NAC rows exist since 18 Sep, so
# the words are allowed - but never next to MiLOI or fore/aft, which are the SAME sensor
# (checked below, sentence by sentence; claim-checker checks the rest).
BANNED = ("<", "Your Team Name", "Idea submission", "62,519", "43.9", "0.7 px",
          "cross sensor", "SNPSU")
SAME_SENSOR_WORDS = ("MiLOI", "fore vs aft", "fore/aft", "NAC pairs")


def _audit_deck(deck) -> list[str]:
    """Everything about the built file that a machine can check, checked on every run.

    This exists because the deck was corrected one defect at a time over several rounds -
    template footer, off-canvas figure text, 4.5 pt chart labels, ° rendered through an
    East-Asian fallback, bullets with no hanging indent, an asymmetric right margin. Each
    was found by a human looking at a slide. Everything below is now found by the build.
    """
    bad: list[str] = []
    if len(deck.slides) != 6:
        bad.append(f"slide count is {len(deck.slides)}, must be 6 including the title page")

    band_l, band_r, band_b = 0.54, 12.79, 6.96
    for i, slide in enumerate(deck.slides, 1):
        ours = [sh for sh in slide.shapes
                if not sh.is_placeholder and sh.shape_type != 13
                and sh.has_text_frame and sh.text_frame.text.strip()
                and "Proposed Solution" not in sh.text_frame.text
                and "Technologies to be used" not in sh.text_frame.text
                and "Analysis of the feasibility" not in sh.text_frame.text
                and "Potential impact" not in sh.text_frame.text
                and "Details / Links" not in sh.text_frame.text
                and sh.text_frame.text.strip() != TEAM_NAME]
        pics = [sh for sh in slide.shapes if sh.shape_type == 13
                and Emu(sh.width).inches > 3]

        # Slide 1 is the template's own title layout - its metadata block sits at 0.36 in
        # and there is no footer bar - so the content band applies to slides 2-6 only.
        for sh in (ours + pics) if i > 1 else []:
            l, r = Emu(sh.left).inches, Emu(sh.left).inches + Emu(sh.width).inches
            b = Emu(sh.top).inches + Emu(sh.height).inches
            if l < band_l or r > band_r:
                bad.append(f"slide {i}: a shape spans {l:.2f}..{r:.2f} in, outside the "
                           f"{band_l:.2f}..{band_r:.2f} in content band")
            if b > band_b:
                bad.append(f"slide {i}: a shape reaches {b:.2f} in, into the footer bar")

        # A figure and a text box must not share space.
        for pic in pics:
            pl, pr = Emu(pic.left).inches, Emu(pic.left).inches + Emu(pic.width).inches
            pt_, pb = Emu(pic.top).inches, Emu(pic.top).inches + Emu(pic.height).inches
            for tb in ours:
                tl, tr = Emu(tb.left).inches, Emu(tb.left).inches + Emu(tb.width).inches
                tt, tb_ = Emu(tb.top).inches, Emu(tb.top).inches + Emu(tb.height).inches
                if pl < tr and tl < pr and pt_ < tb_ and tt < pb:
                    bad.append(f"slide {i}: figure and text box overlap")

        for sh in ours:
            ends = []
            for p in sh.text_frame.paragraphs:
                if not p.text.strip():
                    continue
                pPr = p._p.find(qn("a:pPr"))
                bulleted = pPr is not None and pPr.find(qn("a:buChar")) is not None
                if bulleted:
                    ends.append(p.text.rstrip().endswith("."))
                    mar_l = int(pPr.get("marL") or 0)
                    ind = int(pPr.get("indent") or 0)
                    if mar_l <= 0 or ind >= 0:
                        bad.append(f"slide {i}: a bullet has no hanging indent "
                                   f"(marL={mar_l}, indent={ind}); wrapped lines will sit "
                                   f"under the bullet")
                for r in p.runs:
                    rPr = r._r.find(qn("a:rPr"))
                    faces = {t: (rPr.find(qn(f"a:{t}")).get("typeface")
                                 if rPr is not None and rPr.find(qn(f"a:{t}")) is not None
                                 else None)
                             for t in ("latin", "ea", "cs")}
                    if set(faces.values()) != {BODY_FONT}:
                        bad.append(f"slide {i}: run {r.text[:28]!r} has fonts {faces} - a "
                                   f"missing ea/cs face sends ° and × through font linking")
            if len(set(ends)) > 1:
                bad.append(f"slide {i}: bullets in one box mix terminal full stops "
                           f"({sum(ends)} with, {len(ends) - sum(ends)} without)")

        text = " ".join(sh.text_frame.text for sh in slide.shapes if sh.has_text_frame)
        for word in BANNED:
            if word in text:
                bad.append(f"slide {i}: banned text {word!r} is on the slide")
        # Invariant 2: a same-sensor pair (MiLOI, TMC-2 fore/aft) is never cross-sensor or
        # multi-modal. Checked per sentence, so "same-sensor NAC pairs (MiLOI)" passes and
        # "cross-sensor MiLOI pairs" does not.
        for sent in re.split(r"(?<=[.;])\s+", text):
            if any(w in sent for w in SAME_SENSOR_WORDS) and re.search(
                    r"cross-sensor|multi-modal", sent, re.I):
                bad.append(f"slide {i}: same-sensor pair called cross-sensor/multi-modal: "
                           f"{sent[:60]!r}")
        n_tbd = text.count("TBD")
        if n_tbd:
            bad.append(f"slide {i}: {n_tbd} [TBD] placeholder(s) - fill from the freeze commit")

    all_text = " ".join(sh.text_frame.text for s in deck.slides for sh in s.shapes
                        if sh.has_text_frame)
    for need in (TEAM_ID, TEAM_NAME, "SIH26166"):
        if need not in all_text:
            bad.append(f"{need!r} does not appear anywhere in the deck")
    return bad


def _check_pointers(template, deck) -> bool:
    """Every pointer text on every content slide must survive unchanged (whitespace aside)."""
    ok = True
    for i in range(1, 6):
        want = [_norm(sh.text_frame.text) for sh in template.slides[i].shapes
                if sh.has_text_frame and sh.text_frame.text.strip()
                and not any(s in sh.text_frame.text for s in TEMPLATE_STRINGS_WE_SET)]
        have = [_norm(sh.text_frame.text) for sh in deck.slides[i].shapes if sh.has_text_frame]
        for w in want:
            if w not in have:
                print(f"  !! slide {i + 1}: template text altered or missing: {w[:70]!r}")
                ok = False
    return ok


def build() -> int:
    if not TEMPLATE.exists():
        print(f"missing {TEMPLATE} - download the official template first")
        return 2
    prs = Presentation(str(TEMPLATE))

    # ---- slide 1: the metadata block, keeping the template's own labels ----
    s1 = prs.slides[0]
    meta = None
    for sh in s1.shapes:
        if sh.has_text_frame and "Problem Statement ID" in sh.text_frame.text:
            meta = sh
            break
    if meta is not None:
        tf = meta.text_frame
        tf.clear()
        for i, (label, value) in enumerate(TITLE_META):
            para = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            _set_bullet(para, None, 0.0, 0.0)
            r1 = para.add_run()
            r1.text = f"{label} "
            r1.font.size = Pt(15)
            r1.font.bold = True
            r1.font.color.rgb = MUTED
            _set_run_font(r1)
            r2 = para.add_run()
            r2.text = value
            r2.font.size = Pt(15)
            r2.font.bold = False
            r2.font.color.rgb = INK
            _set_run_font(r2)
            para.space_after = Pt(8)

    # ---- content slides ----
    words = {}
    for idx, spec in SLIDES.items():
        slide = prs.slides[idx - 1]

        # The template's oval is a placeholder for the team name; fill it, keep its style.
        oval = _team_oval(slide)
        if oval is not None:
            paras = oval.text_frame.paragraphs
            first = paras[0]
            if first.runs:
                first.runs[0].text = TEAM_NAME
                _set_run_font(first.runs[0])
                for r in first.runs[1:]:
                    r.text = ""
            else:
                first.text = TEAM_NAME
            for p in paras[1:]:
                p._p.getparent().remove(p._p)

        # Clear the "@SIH Idea submission- Template" footer; the bar and page number stay.
        ft = _footer(slide)
        if ft is not None:
            ft.text_frame.clear()
            ft.text_frame.paragraphs[0].add_run().text = ""

        # Move the official pointer text under the title bar, small and grey. TEXT UNCHANGED.
        pb = _pointer_box(slide)
        if pb is not None:
            pb.left, pb.top = Inches(POINTER_BOX[0]), Inches(POINTER_BOX[1])
            pb.width, pb.height = Inches(POINTER_BOX[2]), Inches(POINTER_BOX[3])
            tfp = pb.text_frame
            tfp.word_wrap = True
            try:
                tfp.auto_size = None
            except Exception:
                pass
            # Slide 2's pointer box carries two EMPTY paragraphs sized 32 pt that alone open
            # an 80 px hole. They carry no pointer text, so removing them changes no pointer;
            # only whitespace goes. `_check_pointers` compares whitespace-normalised text.
            for para in list(tfp.paragraphs):
                if not para.text.strip():
                    para._p.getparent().remove(para._p)
            for para in tfp.paragraphs:
                para.space_before = Pt(0)
                para.space_after = Pt(0)
                para.line_spacing = 0.85
                para.font.size = Pt(8)
                para.font.italic = True
                para.font.color.rgb = MUTED
                for run in para.runs:
                    run.font.size = Pt(8)
                    run.font.italic = True
                    run.font.bold = False
                    run.font.color.rgb = MUTED

        if "fig" in spec:
            _add_fig(slide, spec["fig"], spec.get("fig_top"))
        words[idx] = sum(_add_text(slide, box, items, hp, bp)
                         for box, items, hp, bp in spec["text"])

    _delete_slide(prs, 6)          # the instructions slide, which itself says we may
    prs.save(str(OUT))

    deck = Presentation(str(OUT))
    pointers_ok = _check_pointers(Presentation(str(TEMPLATE)), deck)
    problems = _audit_deck(deck)
    print(f"  wrote {OUT.name}  ({OUT.stat().st_size:,} bytes, {len(deck.slides)} slides)")
    print("  words of ours per slide: " + " · ".join(f"s{k}={v}" for k, v in sorted(words.items())))
    print(f"  pointer text unchanged on every content slide: {'YES' if pointers_ok else 'NO'}")
    if problems:
        print(f"  AUDIT: {len(problems)} problem(s)")
        for line in problems:
            print(f"    !! {line}")
    else:
        print("  AUDIT: clean - geometry, fonts, bullets, punctuation, banned terms")
    print("  NEXT: export to PDF - the portal accepts PDF only, not .pptx")
    print("        PowerPoint: File > Save As > PDF   (or Print > Microsoft Print to PDF)")
    return 0 if (pointers_ok and not problems) else 1


if __name__ == "__main__":
    raise SystemExit(build())
