"""Build the SIH26166 deck into the official template, from the content in this folder.

    python -m presentation.build_deck

Inputs   presentation/sih_template.pptx   (924,505 bytes, sha256 ce3e5dee...)
         presentation/figures/*.png|jpg   (generated by presentation.make_figures, plus the two
                                           made once by hand - see FIGURES NOT FROM make_figures)
Output   presentation/SIH26166_LunaXX_deck.pptx   (national round, v10 - 27 Sep 2026)

V10 (27 Sep, the SPOC's review of v9): "Everything is OK. But need to check fonts and size. Use
common font for all slides and increase the size of letters. Some slides feel over crowded with
words." All three were true. v9 used four faces (Garamond and Times New Roman from the template's
titles, Calibri for ours, DejaVu Sans inside the two charts), set text as small as 9 pt, and carried
230 / 195 / 330 / 230 words on slides 2-5. V10: Calibri on every run of every slide and in the
charts (`_one_font`, make_figures' FIG_FONT), an 11 pt floor with body text at 12-14 pt, and the
words cut by about 40% - no measured fact was added, and none changed. Slide 3's prototype is the
current workbench (web/), which registers images live, not the retired console.

V9 (NATIONAL ROUND, 23 Sep - the template-and-visuals pass). V8 was correct and still read as
prose: 240 words on slide 2, 207 on slide 4, grey copies of the template's prompts on every
slide, "TITLE PAGE" and "IDEA TITLE" printed as if they were our headings. Before changing
anything, 32 idea decks on the 2024/25 template were rendered and read, and every PS id was
checked against the official 2024 and 2025 Grand Finale results pages - only three are
verifiable national winners (Cannon Crew 2024 SIH1686, ExpertChain 2024 SIH1788, Ourobonics
2025 SIH25117); the "winning PPTs" repos label far more than that. What they show:

  * slide 1: none of the three winners kept "TITLE PAGE"; ExpertChain put the idea name there.
    Ours now carries the idea title (the portal's own "idea title" field) in that placeholder.
  * slide 2: 21 of 32 decks and all three winners replace "IDEA TITLE" with the idea's name.
    It is the slide's title placeholder, not one of the pointer prompts. Replaced.
  * the grey pointer prompts: 0 of 32 decks leave them as small prompt text. Winners turn them
    into their section headings (Cannon Crew: chevron tabs carrying the pointer wording). No
    source was found - SIH FAQ, the 2026 guidelines, forums - of any deck penalised for it.
    So the template's pointer boxes are removed and EVERY POINTER BECOMES A HEADING TAB, in the
    template's words and order (a trailing parenthetical of examples, "(e.g. programming
    languages ...)", is guidance and is dropped where it would not fit a tab; the one with a
    list that IS the content - "Benefits ... (social, economic, environmental, etc.)" - keeps
    it). `_check_pointers` proves every pointer is on its slide as a heading, on every run.
  * the blue footer bar: kept by 29 of 32 and by all three winners. It is the template's own
    design and it stays. Its "@SIH Idea submission- Template" text is cleared, as Cannon Crew
    (winner) did - printing "Template" on a finished submission helps nobody.
  * text: winners are not sparse (~143 and ~198 words a slide) but every one carries a real
    diagram. The SIH 2026 SPOC guidelines, p.13, name the criteria: "novelty of the idea,
    complexity, clarity and details in the prescribed format, feasibility, practicability,
    sustainability, scale of impact, user experience and potential for future work
    progression". V8 had nothing for user experience (no prototype on any slide) and one line
    for future work. V9 draws: the standard-vs-ours flow (2), the pipeline as native shapes
    with a prototype screenshot (3), a PS-requirement scorecard and a risk -> strategy map (4),
    an impact flow, a per-region illustration and four benefit cards (5), and numbered
    references with a QR code to the repository (6).

Every number on a slide is still copied from REPORT.md (the comment beside it names the section),
no figure was added that V8's claim-check had not already cleared, and the one quotation from
SAC's 2026 paper is now a paraphrase with its citation - word-for-word text from a published
paper is what an automated similarity check flags, cited or not.

FIGURES NOT FROM make_figures (made once, 23 Sep, committed):
  fig8_console.jpg  the workbench (`python -m web.server`, 27 Sep, 1200 x 860 at 2x) after a live
                    run of sac_ohrc_nac_w06 from its files: the controls and the trust-map plate,
                    cropped (0, 0, 2372, 1704) and resized to 1400 px. The facts column is outside
                    the crop, and the run's timing sentence was removed from the page before the
                    capture: a live run's counts and seconds differ from the logged row (4,182 vs
                    4,179 inliers), and only logged figures go on a slide.
  qr_console.png    segno 1.6.6, make('https://samarthputhraya.github.io/sih26166/', error='m'), 2 Oct;
  qr_repo.png       segno 1.6.6, make('https://github.com/samarthputhraya/sih26166', error='m'),
                    scale 12, border 2, dark #1F3A5F. Decodes to the repository URL on slide 6.

WHAT THE OFFICIAL INSTRUCTIONS SLIDE SAYS, and how each line is honoured:
  "Kindly keep the maximum slides limit up to six (6). (Including the title slide)"
      -> exactly 6; the instructions slide itself says it may be deleted, and is.
  "Try to avoid paragraphs and post your idea in points /diagrams /Infographics /pictures"
      -> no paragraph anywhere; every content slide is diagrams, cards and short lines.
  "You can only use provided template ... without changing the idea details pointers"
      -> the template (title bar, logo, team-name oval, footer bar, slide order and titles 3-6)
         is used as supplied; the pointers are kept word for word as the headings (above).
  "You need to save the file in PDF and upload the same on portal."
      -> `python -m presentation.export_pdf`.

Layout facts of the template (measured with python-pptx): slide 13.33 x 7.5 in · "Your Team
Name" oval at (0.36, 0.28) 1.37 x 0.88 in · title placeholder y -0.05..1.20 · SIH logo at
(10.70, 0) 2.46 x 1.16 in · footer bar from y 6.95 (fill 0070C0). Our content lives in the
band x 0.55..12.78, y 1.33..6.85.

HISTORY. V4-V8 (20-22 Sep) rebuilt the text around the real-data evidence and survived two
claim-check passes; V8's last fix restored "160 distinct ground windows / 8 instrument
pairings", which a cut had dropped from every slide - it is on slides 2 and 4 now. The
college-round deck (SIH26166_deck.pptx) is not overwritten; the pre-audit v2 is tagged
submission-v1.

Audience (national round): SAC-ISRO image-processing scientists reading the PDF cold, ranking
it against every other SIH26166 idea. What they can check in ten seconds: the pair ids from
their own paper (arXiv:2509.04775, Table 1), and whether "cross-sensor" / "multi-modal" /
"sub-pixel" are used the way Invariant 2 defines them.
"""
from __future__ import annotations

import pathlib
import re
import subprocess
import sys

from PIL import Image, ImageFont
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_CONNECTOR, MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, MSO_AUTO_SIZE, PP_ALIGN
from pptx.oxml.ns import qn
from pptx.util import Emu, Inches, Pt

HERE = pathlib.Path(__file__).resolve().parent
TEMPLATE = HERE / "sih_template.pptx"
FIGURES = HERE / "figures"
OUT = HERE / "SIH26166_LunaXX_deck.pptx"

INK = RGBColor(0x1A, 0x1A, 0x1A)
MUTED = RGBColor(0x5F, 0x6B, 0x7A)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
NAVY = RGBColor(0x1F, 0x3A, 0x5F)
BLUE = RGBColor(0x00, 0x70, 0xC0)          # the template's own footer blue
ACCENT = RGBColor(0xC2, 0x4A, 0x1E)        # ours: the area check, refusals
GREEN = RGBColor(0x1E, 0x7F, 0x4F)         # verified / accepted
AMBER = RGBColor(0xB9, 0x7A, 0x0B)         # unconfirmed / a measured limit
TITLE_BLUE = RGBColor(0x1F, 0x49, 0x7D)    # the template's tx2, "SMART INDIA HACKATHON 2026"
FILL_BLUE, LINE_BLUE = RGBColor(0xEA, 0xF2, 0xFB), RGBColor(0xA9, 0xC8, 0xEA)
FILL_ORANGE, LINE_ORANGE = RGBColor(0xFC, 0xEE, 0xE8), RGBColor(0xE9, 0xB4, 0x9E)
FILL_GREEN, LINE_GREEN = RGBColor(0xE8, 0xF5, 0xEE), RGBColor(0x9F, 0xD1, 0xB5)
FILL_AMBER, LINE_AMBER = RGBColor(0xFD, 0xF4, 0xE1), RGBColor(0xE8, 0xC9, 0x7E)
FILL_GREY, LINE_GREY = RGBColor(0xF3, 0xF5, 0xF8), RGBColor(0xC9, 0xD1, 0xDB)

# EVERY run we write names its font for latin, East Asian AND complex-script ranges.
#
# The template's theme declares <a:latin typeface="Calibri"/> but leaves <a:ea/> and <a:cs/>
# EMPTY. A run that inherits that has no font for any glyph PowerPoint classifies outside the
# latin range, so it resolves ° and × through font linking to a system East Asian face with
# full-width metrics - which is why the 9 Sep build rendered "at a 15°   sun difference". Calibri
# carries every character this deck uses (° × ± → ↔ ≤ — – · “ ”), so naming it in all three
# ranges removes the fallback entirely.
BODY_FONT = "Calibri"
# ONE face for everything, titles included (SPOC review, 27 Sep: "use common font for all
# slides"). The template sets its slide titles in Times New Roman and the title page's "SMART
# INDIA HACKATHON 2026" in Garamond; `_one_font` re-sets every run on every slide to Calibri, and
# the audit fails the build if any run anywhere names another face.
TITLE_FONT = BODY_FONT

# National-round portal values. The team name on the portal is LunaXX (nominated 18 Sep; the
# 2026 guidelines forbid the institute's name in a team name - the college-round deck said
# "SNPSU LunaX"). The Team ID is the portal's, as Samartha read it on 20 Sep: SNPSU0192.
TEAM_ID = "SNPSU0192"
TEAM_NAME = "LunaXX"

# The idea title, as typed into the portal's "idea title" field (the long
# form, first clause). Slide 1 and slide 2 both carry it, so the PDF and the portal agree.
IDEA_TITLE = "Lunar Image Registration That Knows When It Is Wrong"
IDEA_TITLE_LINES = ("Lunar Image Registration", "That Knows When It Is Wrong")
# "region by region", not "every region": the 112-px IIRS windows get a whole-frame verdict
# (claim-check, v6), so "a verdict on every region of every result" is not true of all of them.
# Not "Sun-, scale- and sensor-robust" (v9 claim-check M8): OHRC -> TMC-2 at 120° and TC -> IIRS
# are refused, and 0 of 12 sweep windows at 60-120° are accepted - slide 4 says so.
IDEA_SUBTITLE = "Chandrayaan-2 matching across Sun, scale and sensor — with a verdict region by region"

# Labels copied from the template's own title block, separator included, rather than reworded
# with colons: the template writes "Problem Statement ID –", "Theme-", "Team Name (Registered on
# portal)". Only the values after them are ours.
TITLE_META = [
    ("Problem Statement ID –", "SIH26166"),
    ("Problem Statement Title-", "Multi-modal, Sun angle and scale invariant image "
                                 "correspondence using Chandrayaan-2 optical images "
                                 "(OHRC, TMC and IIRS)"),
    ("Theme-", "Space Technology"),
    ("PS Category-", "Software"),
    ("Team ID-", TEAM_ID),
    ("Team Name (Registered on portal)-", TEAM_NAME),
]

# The template's pointer prompts, per slide, as HEADINGS: exactly the template's words, in its
# order. `_check_pointers` reads the template itself and fails the build if one is missing.
HEADINGS = {
    2: ("Proposed Solution", "Detailed explanation of the proposed solution",
        "How it addresses the problem", "Innovation and uniqueness of the solution"),
    3: ("Methodology and process for implementation", "Technologies to be used"),
    4: ("Analysis of the feasibility of the idea", "Potential challenges and risks",
        "Strategies for overcoming these challenges"),
    5: ("Potential impact on the target audience",
        "Benefits of the solution (social, economic, environmental, etc.)"),
    6: ("Details / Links of the reference and research work",),
}

# ---------------------------------------------------------------------------------------------
# Drawing primitives. Every shape we add is named "lx ..." so the audit can tell ours from the
# template's. Theme styles are stripped from every autoshape and connector: the template's
# effect styles would add shadows, and its font reference would make our text white-on-accent.
# ---------------------------------------------------------------------------------------------
_FONT_FILES = {False: "C:/Windows/Fonts/calibri.ttf", True: "C:/Windows/Fonts/calibrib.ttf"}
_font_cache: dict = {}


def _text_width_in(text: str, size_pt: float, bold: bool) -> float:
    """Width of one line of Calibri in inches - measured, so tabs and chips fit their words."""
    key = (bold, size_pt)
    if key not in _font_cache:
        try:
            _font_cache[key] = ImageFont.truetype(_FONT_FILES[bold], int(round(size_pt * 10)))
        except OSError:
            _font_cache[key] = None
    f = _font_cache[key]
    if f is None:                                    # no Calibri on this machine: estimate
        return len(text) * size_pt * (0.55 if bold else 0.5) / 72
    return f.getlength(text) / 10 / 72


def _set_run_font(run, name=BODY_FONT):
    """Name the font for the latin, East Asian and complex-script ranges of one run.

    `run.font.name` writes only <a:latin>. Leaving <a:ea>/<a:cs> to be inherited from a theme
    that declares them empty is what sent ° and × through East-Asian font linking. Element
    order inside <a:rPr> is fixed by the schema: latin, then ea, then cs.
    """
    run.font.name = name
    rPr = run._r.get_or_add_rPr()
    for tag in ("a:ea", "a:cs"):
        for el in list(rPr.findall(qn(tag))):
            rPr.remove(el)
    after = rPr.find(qn("a:latin"))
    for tag in ("a:ea", "a:cs"):
        el = rPr.makeelement(qn(tag), {"typeface": name})
        if after is not None:
            after.addnext(el)
        else:
            rPr.append(el)
        after = el


def _set_bullet(para, char, mar_l, indent):
    """A real PowerPoint bullet with a hanging indent (or buNone), never a typed "•"."""
    pPr = para._p.get_or_add_pPr()
    pPr.set("marL", str(int(Inches(mar_l))))
    pPr.set("indent", str(int(Inches(indent))))
    for tag in ("a:buNone", "a:buChar", "a:buAutoNum", "a:buFont"):
        for el in list(pPr.findall(qn(tag))):
            pPr.remove(el)
    new = ([pPr.makeelement(qn("a:buNone"), {})] if char is None
           else [pPr.makeelement(qn("a:buFont"), {"typeface": BODY_FONT}),
                 pPr.makeelement(qn("a:buChar"), {"char": char})])
    anchor = pPr.find(qn("a:defRPr"))
    for el in new:
        if anchor is not None:
            anchor.addprevious(el)
        else:
            pPr.append(el)


NBSP = chr(0xA0)
_UNIT = re.compile(r"(?<=\d) (?=(?:m/px|km²|km|nm|px|m|s|MB)(?:[^\w]|$))")


_TO = f"{NBSP}→{NBSP}"             # "NAC → TMC-2" stays on one line
_EQ = f"{NBSP}={NBSP}"             # "0.36–0.48 px = 1.6–2.2 m" never starts a line with "="


def R(text, size, bold=False, colour=INK, italic=False):
    """One run: (text, size pt, bold, colour, italic). A number keeps its unit on its line."""
    return (_UNIT.sub(NBSP, text), size, bold, colour, italic)


def _wrap(text: str, size_pt: float, bold: bool, width_in: float) -> list[str]:
    """`text` broken at spaces into lines no wider than `width_in`, NBSPs joining as R() sets them.

    Joined with "\\n" (a line break, see _fill_text) the lines are ours, not PowerPoint's: it also
    breaks after an en dash, and on 2 Oct it set "1.6–" and "2.2 m" on two lines of slide 4.
    PowerPoint's Calibri is ~0.6 % wider than this measure (the v11 PDF), so wrap a little
    narrower than the box and PowerPoint never has to break a line itself."""
    lines, cur = [], ""
    for w in _UNIT.sub(NBSP, text).split(" "):
        trial = f"{cur} {w}" if cur else w
        if cur and _text_width_in(trial.replace(NBSP, " "), size_pt, bold) > width_in:
            lines.append(cur)
            cur = w
        else:
            cur = trial
    return lines + [cur]


def P(*runs, align="l", sb=0, sa=0, ls=1.0):
    """One paragraph of runs."""
    return {"runs": runs, "align": align, "sb": sb, "sa": sa, "ls": ls}


_ALIGN = {"l": PP_ALIGN.LEFT, "c": PP_ALIGN.CENTER, "r": PP_ALIGN.RIGHT}
_ANCHOR = {"t": MSO_ANCHOR.TOP, "m": MSO_ANCHOR.MIDDLE, "b": MSO_ANCHOR.BOTTOM}


def _fill_text(tf, paras, anchor="t", margins=(0.06, 0.03, 0.06, 0.03)):
    tf.word_wrap = True
    tf.auto_size = MSO_AUTO_SIZE.NONE
    tf.vertical_anchor = _ANCHOR[anchor]
    tf.margin_left, tf.margin_top, tf.margin_right, tf.margin_bottom = (Inches(m) for m in margins)
    for i, p in enumerate(paras):
        para = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        _set_bullet(para, None, 0.0, 0.0)
        para.alignment = _ALIGN[p["align"]]
        para.line_spacing = p["ls"]
        para.space_before = Pt(p["sb"])
        para.space_after = Pt(p["sa"])
        for text, size, bold, colour, italic in p["runs"]:
            # "\n" is a line break inside the paragraph, sized as its run: a bare <a:br> takes the
            # template's body size and would make its line taller than the run's.
            for k, piece in enumerate(text.split("\n")):
                if k:
                    rPr = para._p.add_br().get_or_add_rPr()
                    rPr.set("sz", str(int(round(size * 100))))
                    _set_rpr_font(rPr, BODY_FONT)
                if not piece:
                    continue
                run = para.add_run()
                run.text = piece
                run.font.size = Pt(size)
                run.font.bold = bold
                run.font.italic = italic
                run.font.color.rgb = colour
                _set_run_font(run)


def _strip_style(shape):
    st = shape._element.find(qn("p:style"))
    if st is not None:
        shape._element.remove(st)


def _box(slide, x, y, w, h, paras=(), fill=None, line=None, lw=0.75, kind=MSO_SHAPE.ROUNDED_RECTANGLE,
         radius=0.10, anchor="m", margins=(0.08, 0.04, 0.08, 0.04), name="box"):
    """A shape with optional text. radius is the corner as a fraction of the shorter side."""
    sh = slide.shapes.add_shape(kind, Inches(x), Inches(y), Inches(w), Inches(h))
    sh.name = f"lx {name}"
    _strip_style(sh)
    if kind == MSO_SHAPE.ROUNDED_RECTANGLE:
        sh.adjustments[0] = radius
    if fill is None:
        sh.fill.background()
    else:
        sh.fill.solid()
        sh.fill.fore_color.rgb = fill
    if line is None:
        sh.line.fill.background()
    else:
        sh.line.color.rgb = line
        sh.line.width = Pt(lw)
    _fill_text(sh.text_frame, paras, anchor, margins)
    return sh


def _text(slide, x, y, w, h, paras, anchor="t", margins=(0.0, 0.0, 0.0, 0.0), name="text"):
    tb = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tb.name = f"lx {name}"
    _fill_text(tb.text_frame, paras, anchor, margins)
    return tb


def _arrow(slide, x1, y1, x2, y2, colour=MUTED, w=1.5):
    c = slide.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Inches(x1), Inches(y1),
                                   Inches(x2), Inches(y2))
    c.name = "lx arrow"
    _strip_style(c)
    c.line.color.rgb = colour
    c.line.width = Pt(w)
    ln = c.line._get_or_add_ln()
    ln.append(ln.makeelement(qn("a:tailEnd"), {"type": "triangle", "w": "med", "len": "med"}))
    return c


def _tab(slide, x, y, text, colour=BLUE, size=12.5, h=0.36, w=None):
    """A pointer heading: a home-plate tab in the footer's blue, sized to its words - or to a
    column (`w`), when the words are longer than the column and wrap onto a second line."""
    if w is None:
        w = _text_width_in(text, size, True) + 0.44
    _box(slide, x, y, w, h, [P(R(text, size, True, WHITE))], fill=colour,
         kind=MSO_SHAPE.PENTAGON, anchor="m", margins=(0.12, 0.0, 0.18, 0.0), name="tab")
    return w


def _pic(slide, name, x, y, w=None, h=None, border=None):
    path = FIGURES / name
    if not path.is_file():
        print(f"  !! figure missing: {path.name} - run `python -m presentation.make_figures`")
        return None
    with Image.open(path) as im:
        wp, hp = im.size
    if w is None:
        w = h * wp / hp
    if h is None:
        h = w * hp / wp
    pic = slide.shapes.add_picture(str(path), Inches(x), Inches(y), Inches(w), Inches(h))
    pic.name = f"lx pic {name}"
    if border is not None:
        pic.line.color.rgb = border
        pic.line.width = Pt(0.75)
    return pic


FIG10 = "fig10_site_n.png"
FIG10_DPI = 200                                    # make_figures.SITE_N_DPI


def _native_in(path, default):
    """(width, height) in inches of a figure drawn at FIG10_DPI at its placed size; `default`
    while it is not built (then `_pic` reports it missing)."""
    if not path.is_file():
        return default
    with Image.open(path) as im:
        return im.size[0] / FIG10_DPI, im.size[1] / FIG10_DPI


def _dot(slide, x, y, d, colour):
    return _box(slide, x, y, d, d, fill=colour, kind=MSO_SHAPE.OVAL, name="dot")


# ---------------------------------------------------------------------------------------------
# Slide 1 - title page. The template's metadata block with its own labels, and the idea title
# in the placeholder that said "TITLE PAGE".
# ---------------------------------------------------------------------------------------------
def slide1(s):
    for sh in s.shapes:
        if sh.is_placeholder and sh.has_text_frame and sh.text_frame.text.strip() == "TITLE PAGE":
            sh.left, sh.top, sh.width, sh.height = Inches(0.36), Inches(1.00), Inches(6.9), Inches(1.25)
            tf = sh.text_frame
            for p in list(tf.paragraphs)[1:]:
                p._p.getparent().remove(p._p)
            para = tf.paragraphs[0]
            for r in list(para.runs):
                r._r.getparent().remove(r._r)
            para.alignment = PP_ALIGN.LEFT
            para.line_spacing = 0.95
            tf.word_wrap = True
            tf.vertical_anchor = MSO_ANCHOR.TOP
            tf.margin_left = tf.margin_right = Inches(0)
            for k, line in enumerate(IDEA_TITLE_LINES):
                if k:
                    para.add_line_break()
                run = para.add_run()
                run.text = line
                run.font.size = Pt(32)
                run.font.bold = True
                run.font.color.rgb = TITLE_BLUE
                _set_run_font(run)
    head, tail = IDEA_SUBTITLE.split(" — ")
    _text(s, 0.36, 2.26, 6.9, 0.56, [P(R(head + " —", 15, True, ACCENT)), P(R(tail, 15, True, ACCENT))],
          name="subtitle")

    meta = next((sh for sh in s.shapes
                 if sh.has_text_frame and "Problem Statement ID" in sh.text_frame.text), None)
    if meta is not None:
        meta.top = Inches(2.95)
        tf = meta.text_frame
        tf.clear()
        for i, (label, value) in enumerate(TITLE_META):
            para = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            _set_bullet(para, None, 0.0, 0.0)
            for text, bold, colour in ((f"{label} ", True, MUTED), (value, False, INK)):
                r = para.add_run()
                r.text = text
                r.font.size = Pt(16)
                r.font.bold = bold
                r.font.color.rgb = colour
                _set_run_font(r)
            para.space_after = Pt(8)


# ---------------------------------------------------------------------------------------------
# Slide 2 - the idea. Every number was filled at the evidence freeze from the source in its
# comment (REPORT.md section names are the headings `ops.make_report` writes). Invariant 2:
# OHRC<->NAC / OHRC<->TC are cross-sensor AND cross-mission; NAC<->NAC and TMC-2 fore<->aft are
# SAME sensor; only visible<->infrared (MI, IIRS) and optical<->elevation (LOLA) are multi-modal.
# ---------------------------------------------------------------------------------------------
# How it addresses the problem: the PS's named challenges, one measured line each (v11).
HOW_ROWS = [
    # REPORT.md "SAC's own benchmark pair (equatorial ...)": `agrees` / rows; Δsun az 173.5-173.7,
    # said as 174°. A did-it-register fact, NOT an accuracy comparison.
    ("AZIMUTH", GREEN, "6/6 accepted", " on SAC's pair [1], Suns 174° apart; 0/12 at 60–120°"),
    # "Sun azimuth and elevation, on SAC's own frame": the near-azimuth table's totals line (agrees /
    # windows) and its highest Sun (+41.7° in elevation).
    ("ELEVATION", GREEN, "61/71 accepted", " Sun raised up to 41.7° on SAC's frame"),
    # "Scale rung: ... TC ortho map": scale column, `agrees` / rows.
    ("SCALE", GREEN, "10/10 accepted", " OHRC → TMC-2 across 4.2×; 3/4 across 29.6×"),
    # "TMC-2 -> IIRS, orbit of ..." (both orbits): windows accepted in the bands beyond 850 nm
    # (multi-modal), 8 x 4 on the first orbit + 8 + 8 + 8 + 6 on the second.
    ("MULTI-MODAL", GREEN, "62/62 accepted", " TMC-2 → IIRS infrared, two orbits"),
]


def slide2(s):
    H = HEADINGS[2]
    L, RIGHT = 0.55, 8.95

    _tab(s, L, 1.33, H[0])
    # The thesis, in the first line a judge reads (v9 wording, claim-checked).
    # v11: "Every lunar registration method returns an answer" is no longer true of the field - several
    # public SIH26166 entries refuse - so the thesis states what the matches cannot show and what we add.
    _box(s, L, 1.75, RIGHT - L, 0.76,
         [P(R("A registration can fit its own matches and still be wrong. ", 14, True, INK),
            R("Ours registers Chandrayaan-2 across Sun, scale and sensor, and checks every region", 14, True, ACCENT),
            R(" with evidence the matcher never used.", 14, True, INK))],
         fill=FILL_BLUE, line=LINE_BLUE, anchor="m", margins=(0.16, 0.04, 0.16, 0.04), name="thesis")

    # Detailed explanation: the idea as one flow. The pipeline's own steps are on slide 3.
    _tab(s, L, 2.64, H[1])
    y0, h = 3.04, 1.10
    flow = [(L, 1.30, "Image pair", "Chandrayaan-2 image + lunar reference", FILL_GREY, LINE_GREY, NAVY, MUTED),
            (2.05, 1.55, "Register", "LoFTR matching, MAGSAC++ fit [4, 5]", FILL_GREY, LINE_GREY, NAVY, MUTED),
            (3.80, 1.85, "Independent\narea check", "never reads a match", ACCENT, None, WHITE, WHITE),
            (5.85, 1.45, "Trust map", "verified · weak · no evidence", FILL_BLUE, LINE_BLUE, NAVY, MUTED)]
    for k, (x, w, title, sub, fill, line, tc, sc) in enumerate(flow):
        _box(s, x, y0, w, h, [P(R(t, 13, True, tc), align="c") for t in title.split("\n")]
             + [P(R(sub, 11, False, sc), align="c", sb=2)],
             fill=fill, line=line, margins=(0.07, 0.03, 0.07, 0.03), name="d-step")
        if k:
            _arrow(s, x - 0.20, y0 + h / 2, x - 0.01, y0 + h / 2, colour=ACCENT if k >= 2 else MUTED)
    ox = 7.49
    _arrow(s, 7.30, y0 + h / 2, ox - 0.01, y0 + 0.25, colour=ACCENT, w=1.25)
    _arrow(s, 7.30, y0 + h / 2, ox - 0.01, y0 + h - 0.25, colour=ACCENT, w=1.25)
    _box(s, ox, y0, RIGHT - ox, 0.50, [P(R("accept", 12, True, GREEN), align="c")],
         fill=FILL_GREEN, line=LINE_GREEN, anchor="m", name="d-accept")
    _box(s, ox, y0 + h - 0.50, RIGHT - ox, 0.50, [P(R("refuse → fallback", 12, True, ACCENT), align="c")],
         fill=FILL_ORANGE, line=LINE_ORANGE, anchor="m", margins=(0.04, 0.02, 0.04, 0.02), name="d-refuse")
    # How it addresses the problem: the three PS axes, one measured line each.
    cy = 4.50
    _tab(s, L, cy, H[2])
    cw1 = 3.90
    _box(s, L, cy + 0.38, cw1, 6.85 - cy - 0.38, fill=FILL_GREY, line=LINE_GREY, name="card-how")
    rows = HOW_ROWS
    for k, (label, colour, bold, rest) in enumerate(rows):
        ry = cy + 0.44 + k * 0.48
        _box(s, L + 0.10, ry + 0.08, 1.14, 0.30, [P(R(label, 11, True, WHITE), align="c")],
             fill=colour, radius=0.5, margins=(0.02, 0, 0.02, 0), name="pill")
        _text(s, L + 1.30, ry, cw1 - 1.36, 0.46,
              [P(R(bold, 12, True, INK), R(rest, 12, False, INK))], anchor="m", name="how-row")

    # Innovation and uniqueness: the calibration, both Sun populations, never pooled.
    # "Trust layer on real imagery: planted ...": 0 m row = false alarms; >= 5 m rows all flagged on
    # the 22 near-Sun windows; SAC's 8 flag 84.4 % at 5 m, so that rate is NOT claimed for them
    # (claim-checker M5, v4). The 1-2 m rows are the printed floor.
    ix = L + cw1 + 0.20
    _tab(s, ix, cy, H[3])
    _box(s, ix, cy + 0.38, RIGHT - ix, 6.85 - cy - 0.38, fill=FILL_ORANGE, line=LINE_ORANGE,
         name="card-innovation")
    _text(s, ix + 0.14, cy + 0.46, RIGHT - ix - 0.28, 0.30,
          [P(R("A failure detector, calibrated on real data.", 13, True, INK))], name="inn-lead")
    for k, (num, lab) in enumerate((("0/44", "false alarms on correct answers, Suns within 10° apart"),
                                    ("100%", "of planted 5 m shifts caught (176 trials), same Suns"))):
        ry = cy + 0.80 + k * 0.42
        _text(s, ix + 0.14, ry, 0.86, 0.40, [P(R(num, 24, True, ACCENT))], anchor="m", name="inn-num")
        _text(s, ix + 1.02, ry, RIGHT - ix - 1.16, 0.40, [P(R(lab, 12, False, MUTED))], anchor="m",
              name="inn-lab")
    # Shifts only: rotations and scale changes of 5 m at the corners are flagged far less often
    # at frame level (4 and 8 of 44 near-Sun trials) - slide 5 says why (claim-check v10, H1).
    _text(s, ix + 0.14, cy + 1.68, RIGHT - ix - 0.28, 0.62,
          [P(R("30 real windows. Suns 132–174° apart: 0/16 false alarms, every 10 m "
               "shift caught. At 2 m or less almost nothing is caught: the detection floor.", 12, False, INK))],
          name="inn-body")

    # The trust map itself: SAC's OHRC -> NAC w06 (accepted) above Kaguya TC -> MI 1548 nm w01
    # (refused), through the same code path, re-cached by the freeze's report step.
    _pic(s, "fig3_trust_map.jpg", 9.22, 1.36, w=3.55)


# ---------------------------------------------------------------------------------------------
# Slide 3 - technical approach: core/pipeline.py run_all(), in the order it runs, as native
# shapes; the technologies; the working prototype.
# ---------------------------------------------------------------------------------------------
def slide3(s):
    H = HEADINGS[3]
    L, RIGHT = 0.55, 12.78
    _tab(s, L, 1.33, H[0])

    steps = [("Input pair", "Chandrayaan-2 image + lunar reference"),
             ("Common scale", "one ground grid"),
             ("Illumination", "gradient orientation"),
             ("LoFTR [4]", "dense matching"),
             ("Sub-pixel", "NCC refinement"),
             ("MAGSAC++ [5]", "outlier rejection"),
             ("Coverage", "8×8 spread, uniform GCPs")]
    gap = 0.20
    cw = (RIGHT - L - gap * (len(steps) - 1)) / len(steps)
    y0, h = 1.74, 0.94
    for k, (title, sub) in enumerate(steps):
        x = L + k * (cw + gap)
        _box(s, x, y0, cw, h,
             [P(R(f"{k:02d}" if k else "IN", 11, True, BLUE), align="c"),
              P(R(title, 13, True, NAVY), align="c"),
              P(R(sub, 11, False, MUTED), align="c", sb=1)],
             fill=FILL_BLUE, line=LINE_BLUE, anchor="m", margins=(0.05, 0.03, 0.05, 0.03), name="step")
        if k:
            _arrow(s, x - gap + 0.02, y0 + h / 2, x - 0.02, y0 + h / 2)
    # The point of the diagram, said once. The area check is ours: the only step that never reads
    # a match position, and the only one allowed to overrule the others.
    last_cx = RIGHT - cw / 2
    band_y, band_h = 2.88, 0.72
    _arrow(s, last_cx, y0 + h, last_cx, band_y, colour=ACCENT)
    _box(s, L, band_y, RIGHT - L, band_h,
         [P(R("INDEPENDENT AREA CHECK — ours", 15, True, WHITE), align="c"),
          P(R("cross-correlates the warped image against the reference in 8×8 cells · never reads "
              "a match position · the only step allowed to overrule the rest · builds on [6–9]",
              12, False, WHITE), align="c", sb=1)],
         fill=ACCENT, anchor="m", name="areacheck")
    outs = [("agrees →", " GeoTIFF, uniform control points, trust map", FILL_GREEN, LINE_GREEN, GREEN),
            ("unconfirmed →", " kept and labelled, not certified", FILL_AMBER, LINE_AMBER, AMBER),
            ("contradicted →", " refused; declared fallback in metres", FILL_ORANGE, LINE_ORANGE, ACCENT)]
    og = 0.2
    ow = (RIGHT - L - 2 * og) / 3
    oy = band_y + band_h + 0.18
    for k, (b, rest, fill, line, colour) in enumerate(outs):
        x = L + k * (ow + og)
        _arrow(s, x + ow / 2, band_y + band_h, x + ow / 2, oy, colour=colour)
        _box(s, x, oy, ow, 0.50, [P(R(b, 12.5, True, colour), R(rest, 12.5, False, INK), align="c")],
             fill=fill, line=line, anchor="m", name="outcome")

    # Technologies to be used.
    ty = 4.46
    _tab(s, L, ty, H[1])
    chip_rows = [
        ("Stack", ("Python", "OpenCV", "PyTorch (CPU)", "kornia", "HTML5 console")),
        # v11: no "Methods" row - the pipeline above names every method, and the space goes to
        # the prototype a judge can open.
        ("Data", ("OHRC", "TMC-2", "IIRS", "LRO NAC", "LOLA", "Kaguya TC", "MI")),
    ]
    for k, (label, chips) in enumerate(chip_rows):
        ry = ty + 0.44 + k * 0.45
        _text(s, L, ry, 0.95, 0.36, [P(R(label, 12.5, True, NAVY), align="r")], anchor="m",
              name="chip-label")
        x = L + 1.08
        for c in chips:
            w = _text_width_in(c, 12, False) + 0.26
            _box(s, x, ry, w, 0.36, [P(R(c, 12, False, NAVY), align="c")], fill=FILL_BLUE,
                 line=LINE_BLUE, radius=0.5, margins=(0.04, 0, 0.04, 0), name="chip")
            x += w + 0.08
    # "Runtime and match distribution": median seconds over the 74 deg S OHRC -> NAC windows.
    _box(s, L, 6.30, 8.25, 0.50,
         [P(R("Hardware: ", 12.5, True, ACCENT),
            R("laptop CPU, no GPU, offline — median 7.7 s per 640-px window "
              "(89 OHRC → NAC windows)",
              12.5, False, INK))],
         fill=FILL_ORANGE, line=LINE_ORANGE, anchor="m", margins=(0.14, 0.03, 0.12, 0.03),
         name="hardware")

    # The working prototype (pointer: "Flow Charts/Images/ working prototype"): the published
    # console on a laptop, and the same page on a phone in Hindi (fig8, composed 2 Oct from two
    # screenshots of web/dist/site). The caption is the address, so a judge can open it.
    pic = _pic(s, "fig8_console.jpg", 0, ty, h=2.40, border=LINE_GREY)
    if pic is not None:
        pic.left = Inches(RIGHT) - pic.width
    _box(s, L, ty + 0.44 + 2 * 0.45 + 0.02, 8.25, 0.44,
         [P(R("Try it: ", 12.5, True, NAVY), R("samarthputhraya.github.io/sih26166", 12.5, True, ACCENT),
            R(" · any browser or phone, no install, English or Hindi", 12, False, INK))],
         fill=FILL_BLUE, line=LINE_BLUE, anchor="m", margins=(0.14, 0.03, 0.12, 0.03), name="try-it")


# ---------------------------------------------------------------------------------------------
# Slide 4 - feasibility: the headline figures, the PS's own demands as a scorecard, and each
# measured limit paired with its strategy.
# ---------------------------------------------------------------------------------------------
# v11 (1-3 Oct 2026): the 5 KPI tiles are gone; the PS's own asks are the scorecard, one row each, and
# the Sun is shown in both axes the PS names (fig9: azimuth x elevation on SAC's own OHRC frame).
# Every number is from REPORT.md at the v11 freeze; the comment beside each row names its section.
# REPORT.md "Reproduce" footer: registered pairs and instrument pairings, as printed there (v11
# replaces v10's "160 distinct ground windows / 8 instrument pairings", which REPORT stopped printing).
EVIDENCE_SCALE = ("400 windows", "11 instrument pairings")

SCORECARD = [
    # "SAC's own benchmark pair (equatorial ...)" 6 agrees; "Sun azimuth and elevation ..." opposite table.
    ("Sun azimuth", "SAC's own pair [1]: 6/6 accepted, Sun azimuths 174° apart", GREEN),
    # "Sun azimuth and elevation, on SAC's own frame": the near-azimuth table, its totals line.
    ("Sun elevation", "Same frame, azimuth within 20°: Sun up to 41.7° higher, 61/71 accepted", GREEN),
    # "A real viewpoint test at Site N": agrees / windows, angle apart, held-out median.
    ("Viewpoint", f"OHRC → OHRC, next orbit, views 40° apart: 8/8, held-out 0.91 px{_EQ}1.12 m", GREEN),
    # "Scale rung" 3 agrees of 4; "TMC-2 -> IIRS" scale column 16.2x, every window on both orbits.
    ("Scale", "16× TMC-2 → IIRS: 62/62 · 4.2× OHRC → TMC-2: 10/10 · 29.6× to Kaguya TC: 3/4", GREEN),
    # "TMC-2 -> IIRS", both orbits: bands beyond 850 nm, windows accepted.
    ("Multi-modal", "TMC-2 → IIRS infrared, 999–3223 nm: 62/62, 16 places on two orbits", GREEN),
    # "One site, every camera ... (Site N)": the legs table; then "TMC-2 -> IIRS" on that TMC-2's own
    # orbit (20200607), its four infrared bands' "windows accepted" summed: 8 + 8 + 8 + 6 = 30/30.
    # v11 ended this row "chain via NAC meets direct within 2.0 m": false - the loop's median is 1.99 m,
    # its max 4.04 m, and 2 of its 4 windows are above 2.0 m (audit, 2 Oct). fig10's caption carries
    # the loop with both numbers. Arrows are no-break, so no instrument is cut from its arrow.
    ("OHRC, TMC, IIRS", f"One site, Suns matched: OHRC{_TO}TMC-2 10/10, OHRC{_TO}NAC 5/5, NAC{_TO}TMC-2 4/4; "
                        "IIRS along the same TMC-2 pass: 30/30", GREEN),
    # "Sub-pixel accuracy ... / In the Chandrayaan-2 image's own pixels" (the PS asks for the accuracy
    # "of source image"): NAC <-> TMC-2 at SAC's site, TMC-2 <-> IIRS 1555 nm on orbit 20200607, and
    # OHRC -> NAC at 74 S in OHRC pixels - OHRC is finer than any reference, so it is not sub-pixel in
    # its own pixels, which is why the row is AMBER. 1555 nm is named: 3223 nm reaches 1.2 px. v11 put
    # reference-grid pixels here, which are not the source image's. No figure from SAC's own pair: its
    # paper's SuperGlue number is in-sample, ours are held-out, and the two are not the same measure.
    ("Sub-pixel", f"In the Chandrayaan-2 image's own pixels: TMC-2 0.36–0.48 px{_EQ}1.6–2.2 m; "
                  f"IIRS 1555 nm 0.16–0.32 px{_EQ}13.9–27.3 m; OHRC, finer than NAC, "
                  f"2.0–3.7 px{_EQ}0.51–0.94 m", AMBER),
    # "Runtime and match distribution": grid coverage, and the delivered uniform set.
    ("Uniform spread", "Inliers in ≥95% of 8×8 cells on 17/20 windows; uniform control points ship", GREEN),
    ("Deliverables", "GeoTIFF, GDAL/QGIS control points, ISIS match list, trust map, report", GREEN),
]
RISKS = [
    # "Real sun-angle sweep" bins 60-90 and 90-120: 0 accepted of 7 + 5, none wrongly accepted.
    (("Sun 60–120° away", "0 of 12 accepted: 1 failure caught, 2 right ones refused"),
     ("Choose the pass by its Sun", "How this slide's site was found")),
    (("Relief parallax", "TMC-2 fore → aft, 50° apart: 1 of 4 accepted"),
     ("Local transforms", "Tile-level transforms after DTM orthorectification")),
]


def slide4(s):
    H = HEADINGS[4]
    L, RIGHT = 0.55, 12.78
    ty = 1.33
    tw0 = _tab(s, L, ty, H[0])
    # Two lines by choice: on one, at 3.05 in, it overran its 3.01 in and v11 printed "pairings" alone.
    _text(s, L + tw0 + 0.10, ty, 6.72 - L - tw0 - 0.10, 0.36,
          [P(R("Real data: " + "\n".join(EVIDENCE_SCALE), 11, True, MUTED), align="r")], anchor="m",
          name="evidence-scale")
    y, rg = 1.76, 0.045
    lw, tw = 1.30, 4.82
    for label, text, colour in SCORECARD:
        # Each row's lines are set here (_wrap, at 97 % of the text width), never by PowerPoint,
        # which would split a range at its en dash. Two lines of 11 pt fit 0.455 in; a further
        # line adds one line's height (the sub-pixel row takes three).
        lines = _wrap(text, 11, False, 0.97 * (tw - 0.08 - 0.30))
        rh = 0.455 + 0.19 * max(0, len(lines) - 2)
        _box(s, L, y, lw, rh, [P(R(label, 11.5, True, NAVY), align="c")], fill=FILL_BLUE,
             line=LINE_BLUE, anchor="m", margins=(0.04, 0, 0.04, 0), name="req-label")
        _box(s, L + lw + 0.05, y, tw, rh, [P(R("\n".join(lines), 11, False, INK))], fill=WHITE,
             line=LINE_GREY, anchor="m", margins=(0.08, 0.01, 0.30, 0.01), name="req-text")
        _dot(s, L + lw + 0.05 + tw - 0.24, y + rh / 2 - 0.07, 0.14, colour)
        y += rh + rg
    ly = y + 0.01
    _dot(s, L + lw + 0.05, ly + 0.07, 0.13, GREEN)
    _text(s, L + lw + 0.24, ly, 1.7, 0.26, [P(R("met, as measured", 11, False, MUTED))], name="legend")
    _dot(s, L + lw + 1.90, ly + 0.07, 0.13, AMBER)
    _text(s, L + lw + 2.09, ly, 2.6, 0.26, [P(R("a measured limit", 11, False, MUTED))], name="legend")

    # Every Chandrayaan-2 camera the PS names, at one site, each leg checked (REPORT "Site N"). v11 draft
    # had fig9 (the Sun map on SAC's frame) here; the scorecard's two Sun rows carry those numbers.
    # fig10 is drawn at the size it is placed (make_figures SITE_N_SIZE), so it goes in at its pixel
    # size / FIG10_DPI, never scaled: its point sizes are then the slide's, 11 pt and up. v11 shrank a
    # 6.6 in drawing to 5.45 in and set its captions at 7.0 and 7.8 pt (audit, 2 Oct).
    fx = 6.82
    fw, fh = _native_in(FIGURES / FIG10, (5.90, 3.50))
    _pic(s, FIG10, fx + (RIGHT - fx - fw) / 2, 1.30, w=fw)
    cy = 1.30 + fh + 0.05                                        # 4.85: the tabs start under the figure
    cw0 = (RIGHT - fx - 0.30) / 2
    sx0 = fx + cw0 + 0.30
    _tab(s, fx, cy, H[1], colour=ACCENT, size=11.5, w=cw0, h=0.50)
    _tab(s, sx0, cy, H[2], colour=GREEN, size=11.5, w=cw0, h=0.50)
    ph, pg = 0.66, 0.05                                          # three lines each; ends at 6.78 in
    for k, ((rt, rb), (st, sb)) in enumerate(RISKS):
        y = cy + 0.56 + k * (ph + pg)
        _box(s, fx, y, cw0, ph, [P(R(rt, 11.5, True, ACCENT)), P(R(rb, 11, False, INK))],
             fill=FILL_ORANGE, line=LINE_ORANGE, anchor="m", margins=(0.08, 0.02, 0.06, 0.02), name="risk")
        _arrow(s, fx + cw0 + 0.02, y + ph / 2, sx0 - 0.02, y + ph / 2, colour=MUTED)
        _box(s, sx0, y, cw0, ph, [P(R(st, 11.5, True, GREEN)), P(R(sb, 11, False, INK))],
             fill=FILL_GREEN, line=LINE_GREEN, anchor="m", margins=(0.08, 0.02, 0.06, 0.02), name="strategy")


# ---------------------------------------------------------------------------------------------
# Slide 5 - impact: who it serves and how, why per-region, the calibration, the benefits.
# ---------------------------------------------------------------------------------------------
def slide5(s):
    H = HEADINGS[5]
    L = 0.55
    _tab(s, L, 1.33, H[0])
    fy, fh = 1.74, 1.62
    _box(s, L, fy, 1.75, fh,
         [P(R("Chandrayaan-2 archive", 12.5, True, NAVY), align="c"),
          P(R("OHRC · TMC-2 · IIRS, with LRO and Kaguya references", 11, False, MUTED), align="c", sb=3)],
         fill=FILL_GREY, line=LINE_GREY, name="imp-source")
    _arrow(s, L + 1.75, fy + fh / 2, 2.48, fy + fh / 2)
    _box(s, 2.48, fy, 1.72, fh,
         [P(R("LunaXX", 16, True, WHITE), align="c"),
          P(R("the aligned image plus a verdict per region", 11.5, False, WHITE), align="c", sb=3)],
         fill=NAVY, name="imp-core")
    targets = [
        ("Landing-site safety", " — hazard maps rest on the alignment"),
        # arXiv:2604.25208 SS VI-VII: radiometric normalisation only; joint geometric frameworks set
        # as future research. PARAPHRASED and cited as [2]: verbatim text is what a similarity
        # check flags.
        ("Seamless mosaics", " — the geometric step SAC's 2026 study leaves open [2]"),
        ("Change detection", " — gated region by region"),
    ]
    tx, tw, th, tg = 4.45, 7.62 - 4.45, 0.50, 0.06
    for k, (b, rest) in enumerate(targets):
        y = fy + k * (th + tg)
        _arrow(s, 4.20, fy + fh / 2, tx, y + th / 2, colour=MUTED, w=1.25)
        _box(s, tx, y, tw, th, [P(R(b, 12, True, NAVY), R(rest, 11.5, False, INK))],
             fill=FILL_BLUE, line=LINE_BLUE, anchor="m", margins=(0.10, 0.02, 0.08, 0.02), name="imp-target")
    _text(s, L, fy + fh + 0.06, 7.05, 0.28,
          [P(R("For ISRO and SAC mission teams, PRADAN data users and planetary scientists.",
               11.5, True, MUTED, True))], anchor="m", name="imp-audience")

    # Why per-region: "Errors that are not translations". Frame contradicted at 3 m: 0 of 120
    # (60 rotation + 60 scale). At 3 m the cells moved > 2 px that are NOT verified are 476/752 = 63 %
    # (rotation) and 469/752 = 62 % (scale); 94 % (94.1 %) pools every rotation and scale trial, 0-20 m.
    # v11 set 94 % beside the 3 m result, as if it were the 3 m figure, and named reference grids
    # (0.93-1.62 m/px) that REPORT does not print for this test (audit, 2 Oct: L4, L6).
    # V8's "105 of 120 still say good" was FALSE (v9 H1) - not used.
    py, ph = 3.80, 1.50
    _box(s, L, py, 7.07, ph, fill=FILL_ORANGE, line=LINE_ORANGE, name="per-region")
    gx, gy, cell = L + 0.16, py + 0.12, 0.13
    for i in range(8):
        for j in range(8):
            d = max(abs(i - 3.5), abs(j - 3.5))
            _box(s, gx + j * cell, gy + i * cell, cell - 0.018, cell - 0.018,
                 fill=GREEN if d < 2.5 else ACCENT, kind=MSO_SHAPE.RECTANGLE, name="grid-cell")
    _text(s, L + 0.08, py + 1.18, 1.2, 0.26,
          [P(R("illustration", 11, False, MUTED, True), align="c")], name="grid-caption")
    _text(s, L + 1.42, py + 0.10, 5.52, 1.32,
          [P(R("Why region by region", 13, True, ACCENT)),
           P(R("Rotation and scale errors move the corners, not the centre. At 3 m of corner "
               "movement a whole-frame check refuses 0 of 120 trials; the 8×8 map refuses to verify "
               "62–63% of the cells moved past 2 px (94% over all trials, up to 20 m).",
               12, False, INK), sb=2)],
          name="per-region-text")

    # "Trust layer on real imagery: planted ...": the figure, both populations, never pooled.
    _pic(s, "fig6_trust_real_calibration.png", 7.85, 1.36, w=4.93)

    # Benefits (social, economic, environmental, etc.).
    by = 5.44
    _tab(s, L, by, H[1])
    # v11: concrete, and each one something a user does or saves (fresh-eyes review, 2 Oct).
    cards = [("SCIENTIFIC", "Mosaics and hazard maps use only pixel-confirmed squares"),
             # Open-source since LICENSE (Apache-2.0) and NOTICE were added on 23 Sep (v9 H3).
             ("ECONOMIC", "Apache-2.0, CPU-only, no licence; results open in QGIS and GDAL"),
             ("SOCIAL", "English and Hindi, in any browser; public data, every number checkable"),
             ("ENVIRONMENTAL", "Runs offline on an existing laptop: no new hardware, no cloud")]
    gap = 0.15
    cw = (12.78 - L - gap * 3) / 4
    for k, (head, body) in enumerate(cards):
        x = L + k * (cw + gap)
        _box(s, x, by + 0.40, cw, 0.32, [P(R(head, 11.5, True, WHITE), align="c")], fill=BLUE,
             kind=MSO_SHAPE.RECTANGLE, anchor="m", name="benefit-head")
        _box(s, x, by + 0.72, cw, 0.69, [P(R(body, 12, False, INK))], fill=FILL_BLUE,
             line=LINE_BLUE, kind=MSO_SHAPE.RECTANGLE, anchor="m", margins=(0.10, 0.03, 0.10, 0.03),
             name="benefit-body")


# ---------------------------------------------------------------------------------------------
# Slide 6 - references, numbered (slides 2-5 cite them as [n]), and the one route off the PDF.
# ---------------------------------------------------------------------------------------------
REFS = [
    ("Lunar domain", [
        ("[1]", "Makharia, Singla, Amitabh, Dube, Sharma — Space Applications Centre (ISRO) and "
                "Manipal University Jaipur, 2025 · arxiv.org/abs/2509.04775"),
        ("[2]", "Singh, Singla, Hemrajani, Dube, Amitabh, Patel — \u201cTowards Seamless Lunar "
                "Mosaics\u201d, Space Applications Centre, 2026 · arxiv.org/abs/2604.25208"),
        ("[3]", "Xie, Liu, Di et al. — Remote Sensing 17(13):2302, 2025 (MiLOI dataset)")]),
    ("Methods we build on", [
        ("[4]", "LoFTR, detector-free local feature matching — Sun et al., CVPR 2021 · "
                "arxiv.org/abs/2104.00680"),
        ("[5]", "MAGSAC++ — Barath et al., CVPR 2020 · arxiv.org/abs/1912.05909")]),
    ("Reliability estimation — the basis of our contribution", [
        ("[6]", "Uss, Vozel, Lukin, Chehdi — IEEE TGRS 2016 · arxiv.org/abs/1602.02720"),
        ("[7]", "Brown & Lowe — IJCV 2007"),
        ("[8]", "Wan, Shao, Li — 2021 · arxiv.org/abs/2106.12738"),
        ("[9]", "Truong et al., PDC-Net — CVPR 2021 · arxiv.org/abs/2101.01710")]),
    ("Data sources and licences", [
        ("", "Chandrayaan-2 OHRC, TMC-2, IIRS — ISRO PRADAN (pradan.issdc.gov.in) · LROC NAC, "
             "LOLA — NASA PDS, public domain"),
        ("", "Kaguya TC and MI — JAXA SELENE archive · MiLOI — github.com/Bin501/CNSFM "
             "(evaluation only)")]),
]

# NOT "in REPORT.md at 7dd4e5b". The freeze MEASURED the rows at 7dd4e5b; REPORT.md was
# regenerated from them afterwards. At 7dd4e5b the report is the previous one, and
# trust_real_calibration.csv does not exist there at all - so the trust figures on slides 2 and
# 5 are provably absent from it. A judge with the repo URL can check that in fifteen seconds.
# Say "measured at". `_audit_deck` verifies any "REPORT.md ... at commit X" claim it finds.
# v11: the 2 Oct freeze re-ran every row at 51a9ad0 and its report step wrote REPORT.md with that
# commit's code, so one commit names both (REPORT.md's own header says so).
# "or a count or sum of its rows": REPORT prints 62/62 (s2, s4), 30/30 (s4) and SAC's pair's 6/6
# (s2, s4) only as the rows they add up from - per band, per window - so "every figure comes from
# REPORT.md" was not literally true (audit, 2 Oct). "Result": a grid size or a place is not one.
PROVENANCE = ("Every result is in REPORT.md, or a count or sum of its rows, measured at the freeze "
              "commit 51a9ad0.")


def slide6(s):
    L = 0.55
    _tab(s, L, 1.33, HEADINGS[6][0])
    paras = []
    for g, (head, items) in enumerate(REFS):
        paras.append(P(R(head, 13, True, BLUE), sb=0 if g == 0 else 8, sa=3))
        for tag, text in items:
            runs = ([R(tag + "  ", 12, True, NAVY)] if tag else []) + [R(text, 12, False, INK)]
            paras.append(P(*runs, sa=3))
    _text(s, L, 1.76, 7.80, 5.08, paras, name="refs")

    # The portal takes only a PS, a title, a description and this PDF - there is no link field -
    # so this card is the ONLY route a judge has from the deck to the code, evidence and report.
    cx, cw = 8.55, 12.78 - 8.55
    _box(s, cx, 1.33, cw, 5.52, fill=FILL_BLUE, line=LINE_BLUE, radius=0.04, name="repo-card")
    _text(s, cx + 0.2, 1.43, cw - 0.4, 0.34,
          [P(R("Try it, then read the code", 13.5, True, NAVY), align="c")], name="repo-head")
    # v11: the QR opens the published console (it works on a phone, in English or Hindi); the
    # repository is one link from there and is printed below it.
    _pic(s, "qr_console.png", cx + (cw - 2.05) / 2, 1.84, w=2.05)
    _text(s, cx + 0.15, 3.92, cw - 0.3, 0.42,
          [P(R("samarthputhraya.github.io/sih26166", 12.5, True, ACCENT), align="c"),
           P(R("code: github.com/samarthputhraya/sih26166", 11.5, False, NAVY), align="c")], name="repo-url")
    _text(s, cx + 0.22, 4.42, cw - 0.44, 2.38,
          [P(R("The pipeline, the evidence logs and REPORT.md, regenerated from them by one command. "
               "Apache-2.0.", 12, False, INK), sa=5),
           P(R("Offline: ", 12, True, NAVY),
             R("python -m web.server registers your own images on a laptop.", 12, False, INK),
             sa=5),
           P(R("Next: ", 12, True, NAVY),
             R("time a whole OHRC strip; Suns 60–120° apart by choosing the pass; relief by DTM "
               "orthorectification; more matched-Sun sites.", 12, False, INK), sa=5),
           P(R(PROVENANCE, 11, False, MUTED), sa=5),
           P(R("Every chart and screenshot is made by our own code; methods and data are credited "
               "on the left.", 11, True, NAVY))],
          name="repo-body")


SLIDE_BUILDERS = {2: slide2, 3: slide3, 4: slide4, 5: slide5, 6: slide6}


# ---------------------------------------------------------------------------------------------
# Template handling
# ---------------------------------------------------------------------------------------------
# The opening words of each content slide's pointer box, from the template.
POINTER_MARKERS = ("Proposed Solution", "Technologies to be used",
                   "Analysis of the feasibility", "Potential impact", "Details / Links")

# Two template strings this build deliberately fills or clears. They are NOT pointer text.
#   "Your Team Name"                  the oval IS a placeholder for the team name; filled.
#   "@SIH Idea submission- Template"  the footer; cleared, keeping the blue bar and page number.
# Evidence for clearing the footer text, gathered 9 Sep and again 23 Sep: Cannon Crew 2024 (a
# verified winner, SIH1686) cleared it; across 32 decks it was kept, cleared and edited about
# equally often. The bar itself stays - 29 of 32 decks and all three verified winners keep it.
TEMPLATE_STRINGS_WE_SET = ("Your Team Name", "Idea submission")


def _pointer_box(slide):
    for sh in slide.shapes:
        if (sh.has_text_frame and not sh.is_placeholder and not sh.name.startswith("lx ")
                and any(m in sh.text_frame.text for m in POINTER_MARKERS)):
            return sh
    return None


def _team_oval(slide):
    for sh in slide.shapes:
        if sh.has_text_frame and sh.text_frame.text.strip() == "Your Team Name":
            return sh
    return None


def _footer(slide):
    for sh in slide.shapes:
        if sh.has_text_frame and "Idea submission" in sh.text_frame.text:
            return sh
    return None


def _set_slide2_title(slide):
    """The title placeholder read "IDEA TITLE" - a label for the idea's own title. Filled."""
    t = slide.shapes.title
    tf = t.text_frame
    for p in list(tf.paragraphs)[1:]:
        p._p.getparent().remove(p._p)
    para = tf.paragraphs[0]
    for child in list(para._p):
        if child.tag in (qn("a:r"), qn("a:br")):
            para._p.remove(child)
    para.line_spacing = 0.9
    for k, line in enumerate(IDEA_TITLE_LINES):
        if k:
            para.add_line_break()
        run = para.add_run()
        run.text = line
        run.font.size = Pt(30)
        run.font.bold = True
        run.font.color.rgb = INK
        _set_run_font(run, TITLE_FONT)


def _one_font(prs):
    """Every run and field on every slide in BODY_FONT - the template's own titles included.

    Only the face changes: size, weight and colour stay as the template or our code set them.
    Group shapes are walked too, and <a:endParaRPr> (the empty paragraph's run properties) is
    set so a caret placed in an empty paragraph does not come back in the old face.
    """
    tags = (qn("a:r"), qn("a:fld"))
    for slide in prs.slides:
        for el in slide.shapes._spTree.iter():
            if el.tag in tags:
                rPr = el.find(qn("a:rPr"))
                if rPr is None:
                    rPr = el.makeelement(qn("a:rPr"), {})
                    el.insert(0, rPr)
                _set_rpr_font(rPr, BODY_FONT)
            elif el.tag == qn("a:endParaRPr"):
                _set_rpr_font(el, BODY_FONT)


def _set_rpr_font(rPr, name):
    """latin, ea and cs faces on one <a:rPr>, in schema order, after any fill or effects."""
    for tag in ("a:latin", "a:ea", "a:cs"):
        for el in list(rPr.findall(qn(tag))):
            rPr.remove(el)
    # Schema order inside rPr: ln, fill, effect, highlight, uLnTx/uLn, uFillTx/uFill, latin, ea,
    # cs, sym, hlinkClick... Insert before the first element that must follow the fonts.
    after = ("a:sym", "a:hlinkClick", "a:hlinkMouseOver", "a:rtl", "a:extLst")
    anchor = next((c for c in rPr if c.tag in {qn(t) for t in after}), None)
    for tag in ("a:latin", "a:ea", "a:cs"):
        el = rPr.makeelement(qn(tag), {"typeface": name})
        if anchor is not None:
            anchor.addprevious(el)
        else:
            rPr.append(el)


def _delete_slide(prs, index):
    xml_slides = prs.slides._sldIdLst
    slides = list(xml_slides)
    rId = slides[index].get(
        "{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id")
    prs.part.drop_rel(rId)
    xml_slides.remove(slides[index])


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


# ---------------------------------------------------------------------------------------------
# Audit
# ---------------------------------------------------------------------------------------------
# "multi-modal" and "cross-sensor" were banned for the college round, when no such real pair
# existed. Real visible<->infrared (Kaguya MI, IIRS) and OHRC<->NAC rows exist since 18 Sep, so
# the words are allowed - but never next to MiLOI or fore/aft, which are the SAME sensor.
BANNED = ("<", "Your Team Name", "Idea submission", "62,519", "43.9", "0.7 px",
          "cross sensor", "SNPSU LunaX", "TITLE PAGE", "IDEA TITLE", "TBD")
SAME_SENSOR_WORDS = ("MiLOI", "fore vs aft", "fore/aft", "NAC pairs")
# Words of ours per content slide, diagram labels included. Slide 4 is a scorecard and a
# risk -> strategy map, so it carries more labels than prose; slide 6 is references.
# v10 (SPOC: "some slides feel over crowded with words"): v9 carried 230 / 195 / 330 / 230.
# Slide 4 kept the qualifiers the v10 claim-check restored (population, azimuth vs Sun vector,
# scope, "from the visible-band fit"): 271 words against v9's 324.
MAX_WORDS = {2: 180, 3: 160, 4: 230, 5: 170}      # a guard, not a target (v11: slide 4 cut from 275; slide 2 gained a row)
TYPE_FLOOR_PT = 11                                 # v9 allowed 9 pt; the SPOC asked for bigger letters


def _ours(slide):
    return [sh for sh in slide.shapes if sh.name.startswith("lx ")]


def _audit_deck(deck) -> list[str]:
    """Everything about the built file that a machine can check, checked on every run."""
    bad: list[str] = []
    if len(deck.slides) != 6:
        bad.append(f"slide count is {len(deck.slides)}, must be 6 including the title page")

    band_l, band_r, band_b = 0.30, 12.79, 6.88
    for i, slide in enumerate(deck.slides, 1):
        ours = _ours(slide)
        for sh in ours if i > 1 else []:
            l, r = Emu(sh.left).inches, Emu(sh.left).inches + Emu(sh.width).inches
            b = Emu(sh.top).inches + Emu(sh.height).inches
            if l < 0.54 - 1e-6 or r > band_r + 1e-6:
                bad.append(f"slide {i}: {sh.name} spans {l:.2f}..{r:.2f} in, outside the "
                           f"0.54..{band_r:.2f} in content band")
            if b > band_b + 1e-6:
                bad.append(f"slide {i}: {sh.name} reaches {b:.2f} in, into the footer bar's margin")
        if i == 1:
            for sh in ours:
                if Emu(sh.left).inches < band_l:
                    bad.append(f"slide 1: {sh.name} starts left of the metadata block")

        # A picture must not share space with any other shape of ours.
        pics = [sh for sh in ours if sh.shape_type == 13]
        for pic in pics:
            # fig10's type is 11-12 pt only at its drawn size (make_figures checks the drawing).
            if pic.name == f"lx pic {FIG10}":
                with Image.open(FIGURES / FIG10) as im:
                    drawn = im.size[0] / FIG10_DPI
                if abs(Emu(pic.width).inches - drawn) > 0.01:
                    bad.append(f"slide {i}: {FIG10} placed {Emu(pic.width).inches:.2f} in wide, drawn "
                               f"{drawn:.2f} in: its type is no longer the 11 pt it was drawn at")
            pl, pr = Emu(pic.left).inches, Emu(pic.left).inches + Emu(pic.width).inches
            pt_, pb = Emu(pic.top).inches, Emu(pic.top).inches + Emu(pic.height).inches
            for o in ours:
                if o is pic:
                    continue
                ol, orr = Emu(o.left).inches, Emu(o.left).inches + Emu(o.width).inches
                ot, ob = Emu(o.top).inches, Emu(o.top).inches + Emu(o.height).inches
                if pl < orr - 0.01 and ol < pr - 0.01 and pt_ < ob - 0.01 and ot < pb - 0.01:
                    if not (o.name == "lx repo-card"):          # the QR sits on its card
                        bad.append(f"slide {i}: {pic.name} overlaps {o.name}")

        # One face on the whole slide, the template's text included; the size floor on ours.
        for el in slide.shapes._spTree.iter():
            if el.tag not in (qn("a:r"), qn("a:fld")):
                continue
            rPr = el.find(qn("a:rPr"))
            faces = {t: (rPr.find(qn(f"a:{t}")).get("typeface")
                         if rPr is not None and rPr.find(qn(f"a:{t}")) is not None else None)
                     for t in ("latin", "ea", "cs")}
            txt = "".join(t.text or "" for t in el.iter(qn("a:t")))
            if txt.strip() and set(faces.values()) != {BODY_FONT}:
                bad.append(f"slide {i}: run {txt[:28]!r} has fonts {faces}, not {BODY_FONT} "
                           f"throughout")
        for sh in ours:
            if not sh.has_text_frame:
                continue
            for p in sh.text_frame.paragraphs:
                for r in p.runs:
                    if r.text.strip() and r.font.size is not None and r.font.size.pt < TYPE_FLOOR_PT:
                        bad.append(f"slide {i}: run {r.text[:28]!r} is {r.font.size.pt} pt, "
                                   f"below the {TYPE_FLOOR_PT} pt floor")

        text = " ".join(sh.text_frame.text for sh in slide.shapes if sh.has_text_frame)
        for word in BANNED:
            if word in text:
                bad.append(f"slide {i}: banned text {word!r} is on the slide")
        for sent in re.split(r"(?<=[.;])\s+", text):
            if any(w in sent for w in SAME_SENSOR_WORDS) and re.search(
                    r"cross-sensor|multi-modal", sent, re.I):
                bad.append(f"slide {i}: same-sensor pair called cross-sensor/multi-modal: "
                           f"{sent[:60]!r}")
        # Provenance: "in REPORT.md AT commit X" says X's tree contains a report holding these
        # figures. Verify the claim if it is made, rather than banning the words.
        for m in re.finditer(r"REPORT\.md[^.]{0,40}?at\s+(?:the\s+\w+[- ]\w+\s+)?commit\s+"
                             r"`?([0-9a-f]{7,40})`?", text, re.I):
            sha = m.group(1)
            got = subprocess.run(["git", "show", f"{sha}:REPORT.md"],
                                 cwd=str(HERE.parent), capture_output=True, text=True)
            missing = [f for f in ("13.1 km", "0.57 m", "8.2 s", "160 distinct")
                       if f not in got.stdout]
            if got.returncode or missing:
                bad.append(f"slide {i}: claims its figures are in REPORT.md at commit {sha}, "
                           f"but that commit's REPORT.md is missing {missing or 'itself'}. "
                           f"Say 'measured at' - the report is regenerated after the freeze")
        n_words = sum(len(sh.text_frame.text.split()) for sh in ours if sh.has_text_frame)
        if n_words > MAX_WORDS.get(i, 10 ** 6):
            bad.append(f"slide {i}: {n_words} words of ours, over its {MAX_WORDS[i]} cap")

    # Whitespace-normalised: a KPI card sets "160" and "distinct ground windows" as two lines.
    all_text = _norm(" ".join(sh.text_frame.text for s in deck.slides for sh in s.shapes
                              if sh.has_text_frame))
    for need in (TEAM_ID, TEAM_NAME, "SIH26166", *EVIDENCE_SCALE):
        if need not in all_text:
            bad.append(f"{need!r} does not appear anywhere in the deck")
    for s in list(deck.slides)[1:]:
        if _pointer_box(s) is not None:
            bad.append("a template pointer box is still on a content slide")
    return bad


def _check_pointers(template, deck) -> bool:
    """Every template pointer is on its slide as a heading of its own, in the template's words.

    A pointer line is accepted verbatim, or without a trailing parenthetical of examples -
    "Technologies to be used (e.g. programming languages, frameworks, hardware)" -> "Technologies
    to be used". Nothing else is: no rewording, no reordering of words, no abbreviation.
    """
    ok = True
    for i in range(1, 6):
        pb = _pointer_box(template.slides[i])
        want = [_norm(p.text) for p in pb.text_frame.paragraphs if p.text.strip()]
        have = {_norm(sh.text_frame.text) for sh in deck.slides[i].shapes if sh.has_text_frame}
        for w in want:
            short = re.sub(r"\s*\([^)]*\)\s*$", "", w)
            if w not in have and short not in have:
                print(f"  !! slide {i + 1}: pointer not present as a heading: {w[:70]!r}")
                ok = False
    return ok


def build() -> int:
    if not TEMPLATE.exists():
        print(f"missing {TEMPLATE} - download the official template first")
        return 2
    prs = Presentation(str(TEMPLATE))
    slide1(prs.slides[0])

    words = {}
    for idx, draw in SLIDE_BUILDERS.items():
        slide = prs.slides[idx - 1]

        # The template's oval is a placeholder for the team name; fill it, keep its style.
        oval = _team_oval(slide)
        if oval is not None:
            paras = oval.text_frame.paragraphs
            first = paras[0]
            if first.runs:
                first.runs[0].text = TEAM_NAME
                _set_run_font(first.runs[0])
                for r in first.runs[1:]:
                    r.text = ""
            else:
                first.text = TEAM_NAME
            for p in paras[1:]:
                p._p.getparent().remove(p._p)

        ft = _footer(slide)
        if ft is not None:
            ft.text_frame.clear()
            ft.text_frame.paragraphs[0].add_run().text = ""

        # The pointer prompts become our heading tabs; the prompt box itself goes.
        pb = _pointer_box(slide)
        if pb is not None:
            pb._element.getparent().remove(pb._element)
        if idx == 2:
            _set_slide2_title(slide)

        draw(slide)
        words[idx] = sum(len(sh.text_frame.text.split()) for sh in _ours(slide)
                         if sh.has_text_frame)

    _delete_slide(prs, 6)          # the instructions slide, which itself says we may
    _one_font(prs)
    prs.save(str(OUT))

    deck = Presentation(str(OUT))
    pointers_ok = _check_pointers(Presentation(str(TEMPLATE)), deck)
    problems = _audit_deck(deck)
    print(f"  wrote {OUT.name}  ({OUT.stat().st_size:,} bytes, {len(deck.slides)} slides)")
    print("  words of ours per slide: " + " · ".join(f"s{k}={v}" for k, v in sorted(words.items())))
    print(f"  every pointer present as a heading: {'YES' if pointers_ok else 'NO'}")
    if problems:
        print(f"  AUDIT: {len(problems)} problem(s)")
        for line in problems:
            print(f"    !! {line}")
    else:
        print("  AUDIT: clean - geometry, one font, 11 pt floor, word caps, banned terms, pointers, "
              "provenance")
    print("  NEXT: python -m presentation.export_pdf  (the portal accepts PDF only)")
    return 0 if (pointers_ok and not problems) else 1


if __name__ == "__main__":
    raise SystemExit(build())
