"""Classical baselines on the SAME sun-sweep pairs our matcher ran on, with exact ground truth.

    python -m baselines.sweep_baselines --dem <dem.npy> --pixel-size 60 \
        --sweep 0,15,30,45 --repeats 5 [--log]

This is **Gate 2 criterion 5**: *">=2x better than the best of SIFT/ORB/AKAZE on the
same pair at the same scale."* It was the last criterion with no evidence.

Four decisions worth defending, because three of them are where this could have
produced a number that looked fine and meant nothing.

1. THE PAIRS ARE NOT REBUILT HERE - THEY ARE REGENERATED BY `core.pipeline._synthetic_pair`,
   THE SAME FUNCTION OUR OWN RUN CALLS. Same DEM, same crop, same sun geometry, same
   off-grid shifts, same seeds, and therefore byte-identical .tif files. "Same pair at
   the same scale" is then true by construction rather than by careful copying. An
   earlier plan for this script re-implemented `make_pair` with its own crater DEM, which
   would have compared our matcher on one set of pixels to SIFT on another and called the
   ratio a result.

2. `evaluate()` GETS THE RAW MATCHES, BEFORE ANY RANSAC. It fits on 80% and scores the
   20% it never saw. Handing it points a RANSAC already accepted makes `inlier_ratio` ask
   "of the points I kept, how many do I keep?" and the answer is always ~1.0. That exact
   bug cost this project a week (Canonical Facts section 7).

3. THE DETECTORS NEED uint8 AND THE PAIRS ARE float32 [0,255]. `_synthetic_pair` writes
   DN-shaped float32. Passing that straight into SIFT/ORB/AKAZE returns near-zero
   keypoints *silently* - no error, just a flattering "classical fails completely". We
   clip and cast, so the baselines get their best honest shot.

4. FAILURES ARE LOGGED, NOT DROPPED (`allow_failed=True`). Classical methods genuinely
   fall over past ~30 degrees of sun difference. A logged failure is the evidence; a
   filtered-out failure is a flattering lie about the comparison.
"""
from __future__ import annotations

import argparse
import pathlib
import statistics
import sys

import numpy as np

from baselines.akaze_baseline import run_akaze
from baselines.orb_baseline import run_orb
from baselines.sift_baseline import run_sift
from core.io_loader import load
from core.pipeline import SYNTH_SHIFT_PX, _draw_shift, _log_preflight, _synthetic_pair
from evaluation.logger import log_result
from evaluation.metrics import evaluate

DETECTORS = (("SIFT", run_sift), ("ORB", run_orb), ("AKAZE", run_akaze))


def u8(img: np.ndarray) -> np.ndarray:
    """float32 DN [0,255] -> uint8. See decision 3 in the module docstring."""
    return np.clip(np.asarray(img, np.float32), 0, 255).astype(np.uint8)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="python -m baselines.sweep_baselines",
                                description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dem", required=True, help="2-D elevation .npy, the same one core.pipeline uses")
    p.add_argument("--pixel-size", type=float, required=True)
    p.add_argument("--sweep", default="0,15,30,45")
    p.add_argument("--repeats", type=int, default=5)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--max-size", type=int, default=640)
    p.add_argument("--log", action="store_true",
                   help="append one row per (pair, detector) to evaluation/results_log.csv")
    p.add_argument("--quiet", action="store_true")
    return p


def main(argv: list[str]) -> int:
    args = build_parser().parse_args(argv[1:])
    deltas = [float(d) for d in args.sweep.split(",") if d.strip()]

    if args.log:
        err = _log_preflight()
        if err:
            print(err)
            return 3

    # rows[detector][delta] = [rmse_gt_px, ...] over the repeats
    rows: dict[str, dict[float, list[float]]] = {n: {d: [] for d in deltas} for n, _ in DETECTORS}

    for d in deltas:
        for rep in range(args.repeats):
            shift = tuple(SYNTH_SHIFT_PX) if rep == 0 else _draw_shift(args.seed + rep)
            src_path, ref_path, H_true, meta = _synthetic_pair(
                args.dem, args.pixel_size, d, shift_px=shift,
                seed=args.seed + rep, max_size=args.max_size)
            src, _ = load(src_path)
            ref, _ = load(ref_path)
            s8, r8 = u8(src), u8(ref)

            for name, fn in DETECTORS:
                src_pts, ref_pts, _conf, elapsed = fn(s8, r8)
                m = evaluate(r8.shape, src_pts, ref_pts, H_true=H_true)
                gt = m.get("rmse_gt_px")
                if gt is not None:
                    rows[name][d].append(float(gt))
                if not args.quiet:
                    print(f"  d{int(d):03d} rep{rep} {name:6s} "
                          f"matches={m.get('n_matches', 0):5d} "
                          f"status={str(m.get('status', '?')):16s} "
                          f"rmse_gt_px={'None' if gt is None else f'{gt:.4f}'}")
                if args.log:
                    log_result(meta["pair_id"], tier="synthetic", method=name, metrics=m,
                               config=meta["config"] + f"; detector={name} (classical baseline)",
                               gsd_mpp=args.pixel_size,
                               notes=("GATE 2 CRITERION 5: classical arm, on the SAME pair our "
                                      "matcher ran on (regenerated by core.pipeline._synthetic_pair, "
                                      f"byte-identical). sun azimuth difference {d:g} deg; "
                                      f"shift=({shift[0]:+.2f},{shift[1]:+.2f}); "
                                      f"{name}_time={elapsed:.3f}s. Raw matches to evaluate(), "
                                      "pre-RANSAC."),
                               allow_failed=True)

    print("\n" + "=" * 78)
    print("  GATE 2 CRITERION 5 - median rmse_gt_px per detector per sun-azimuth delta")
    print("=" * 78)
    hdr = "  delta  " + "".join(f"{n:>12s}" for n, _ in DETECTORS) + f"{'best cls':>12s}"
    print(hdr)
    best_by_delta: dict[float, float] = {}
    for d in deltas:
        line = f"  {int(d):>5d}  "
        meds = []
        for name, _ in DETECTORS:
            vals = rows[name][d]
            if vals:
                med = statistics.median(vals)
                meds.append(med)
                line += f"{med:>12.3f}"
            else:
                line += f"{'no gt':>12s}"
        if meds:
            best_by_delta[d] = min(meds)
            line += f"{min(meds):>12.3f}"
        else:
            line += f"{'-':>12s}"
        print(line)

    print("\n  A number here is the TRUE error against the known homography, in reference")
    print("  pixels. Lower is better. `no gt` means every repeat failed before a transform")
    print("  could be scored - which is itself the finding, and those rows are logged.")
    print("\n  Compare against our own medians from the same pairs (results_log.csv,")
    print("  method ours_loftr+subpixel): 0deg 0.086 | 15deg 0.086 | 30deg 0.314 | 45deg 1.096")
    print("  Gate 2 criterion 5 needs ours to be >=2x better at a stated delta <= 15 deg.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
